######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 17 11:22:18 2006
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ..
CONFIG += staticlib

# Input
HEADERS += condition.hpp logic.hpp mask.hpp
SOURCES += atom.cpp condition.cpp dist.cpp logic.cpp mask.cpp paren.cpp resd.cpp
