######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 13 19:42:48 2006
######################################################################

TEMPLATE = lib 
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ..
CONFIG += staticlib

# Input
HEADERS += parse.hpp reader.hpp status.hpp
SOURCES += parse.cpp reader.cpp status.cpp
