#!/usr/bin/env python


from os import path
from sys import exit, stderr
from string import split


def has_path( files, file ):
    for f in files:
        if( path.samefile(f, file) ) :
            return True
    return False

def list_includes( file ):
    dir = path.dirname( file )

    incs = []

    fin = open( file, "r" )

    line = fin.readline()

    while len(line) > 0:
        if line.find( "#include" ) != -1:
            inc = split(line)[1]
            
            if inc[0] == '"':
                filename = path.join( dir, inc[1:-1] )
                   
                if not path.exists(filename) :
                    
                    filename = "../" + inc[1:-1]
                    if not path.exists(filename): 
                        stderr.write( filename + ' does not exist! listing ' + file + "\n" )
                        exit(-1)  
                if has_path( incs, filename ) == 0:
                    incs.append( filename )

            elif inc[0] =='<':
                inc =  "../" + inc[1:-1]
                if path.exists(inc) and has_path(incs, inc)==0:
                    incs.append( inc )
        line = fin.readline()
    return incs

from sys import argv



for file in  argv[1:]:
    tot_incs = list_includes( file )

    begin = 0
    end  = len( tot_incs )

    while begin < end:
       for i in xrange(begin, end):
            cur_incs = list_includes( tot_incs[i] )
	    #print tot_incs[i], ":", cur_incs
            for inc in cur_incs:
                if has_path( tot_incs, inc ) == 0:
                    tot_incs.append( inc )
       begin = end
       end   = len( tot_incs )

    for i in xrange( len(tot_incs) ):
        print tot_incs[i], "\\"

