phi = doublep()
psi = doublep()
cost = doublep()
phi.assign(1.0)
psi.assign(1.2)
cost.assign(0.91)
rmat = HaMat_double()
rmat.newsize(3,3)
tv = HaMat_double()
vm = HaMat_double()
tv.newsize(3,1)
tv.SetVal(1,1,1.0)
tv.SetVal(2,1,1.1)
tv.SetVal(3,1,1.2)
Rot3D_EulerToRotMat(phi.value(), cost.value(), psi.value(), rmat )
matmult(vm,rmat,tv)
print("transform 1: ", vm.GetVal(1,1), vm.GetVal(2,1), vm.GetVal(3,1))
Rot3D_IncrEulerAng( phi, cost, psi, 0.1,0.1,0.1)
Rot3D_EulerToRotMat(phi.value(), cost.value(), psi.value(), rmat )
matmult(vm,rmat,tv)
print("transform 2: ",vm.GetVal(1,1), vm.GetVal(2,1), vm.GetVal(3,1))
print(rmat.GetVal(1,1), rmat.GetVal(1,2), rmat.GetVal(1,3))
print(rmat.GetVal(2,1), rmat.GetVal(2,2), rmat.GetVal(2,3))
print(rmat.GetVal(3,1), rmat.GetVal(3,2), rmat.GetVal(3,3))
Rot3D_RotMatToEuler(rmat,phi, cost, psi )
print(" New Euler Angles:")
print(phi.value(), cost.value(), psi.value())
