//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: ha_wx_res_2.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_ha_wx_res_2_H__
#define __WDR_ha_wx_res_2_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "ha_wx_res_2_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

#define IDC_INTERMOL_EL_STAT 20000
#define IDC_INTERMOL_TOT_ENE 20001
#define IDC_MC_DOCK_ET_RATE2 20002
#define ID_TEXT_ELECTROSTATIC_MODEL 20003
#define IDC_MC_DOCK_ELECTR_MODEL 20004
#define IDC_INTERMOL_CHANGES_PK 20005
#define ID_TEXT_MOL_1 20006
#define IDC_INTERMOL_INT_COORD_1 20007
#define ID_TEXT_MOL_2 20008
#define IDC_INTERMOL_INT_COORD_2 20009
#define IDC_INTERMOL_SET_INT_COORD 20010
#define IDC_INTERMOL_COMP_INT_COORD 20011
wxSizer *inter_mol_setup_page( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_NOTEBOOK 20012
wxSizer *inter_mol_dlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_TEXT_DEV_IN_CONSTR 20013
#define IDC_DEV_CONST_DIST 20014
#define IDC_TEXT_WEIGHT_1 20015
#define IDC_WEIGHT_CONST_DIST 20016
#define ID_TEXT_PACK_DIST 20017
#define IDC_PACK_DIST 20018
#define ID_TEXT_STD_DEV_1 20019
#define IDC_STDEV_PACK_DIST 20020
#define ID_TEXT_WEIGHT_2 20021
#define IDC_WEIGHT_PACK_DIST 20022
#define ID_TEXT_PACK_ANGLE 20023
#define IDC_PACK_ANGLE 20024
#define ID_TEXT_STD_DEV_2 20025
#define IDC_STDEV_PACK_ANGLE 20026
#define ID_TEXT_WEIGHT_3 20027
#define IDC_WEIGHT_PACK_ANGLE 20028
#define ID_TEXT_DIST_HELIX_CONT 20029
#define IDC_HEL_CONT 20030
#define ID_TEXT_STD_DEV_3 20031
#define IDC_STDEV_HEL_CONT 20032
#define ID_TEXT_WEIGHT_4 20033
#define IDC_WEIGHT_HEL_CONT 20034
#define ID_TEXT_PACKING_DENSITY 20035
#define IDC_PACK_DEN 20036
#define ID_TEXT_STD_DEV_4 20037
#define IDC_STDEV_PACK_DEN 20038
#define ID_TEXT_WEIGHT_5 20039
#define IDC_WEIGHT_PACK_DEN 20040
#define ID_TEXT_DEVIATION_OF_SYMM 20041
#define IDC_SYM 20042
#define ID_TEXT_WEIGHT_6 20043
#define IDC_WEIGHT_SYM 20044
#define ID_TEXT_ANGLE_SA_HELIX 20045
#define IDC_ANG_SA_FACE 20046
#define ID_TEXT_WEIGHT_7 20047
#define IDC_WEIGHT_SA_FACE 20048
#define ID_TEXT_WEIGHT_VDW 20049
#define IDC_WEIGHT_VDW 20050
#define ID_TEXT_VDW_CUTOFF 20051
#define IDC_CUTOFF_VDW 20052
#define IDC_SCORE 20053
#define IDC_RUN_REM 20054
#define ID_TEXT_NUM_REPLICAS 20055
#define IDC_NUM_REPLICAS 20056
#define ID_TEXT_NUM_REM 20057
#define IDC_REM_STEPS 20058
#define ID_TEXT_HIGH_TEMP 20059
#define IDC_HI_TEMP 20060
#define IDC_VAR_TEMP 20061
wxSizer *simulate_anneal_dlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_TEXT_MC_TRAJ_FILE 20062
#define IDC_MC_DOCK_TRAJ_FILE 20063
#define IDC_MC_DOCK_RUN 20064
#define IDC_MC_DOCK_PLAYBACK_TRAJ 20065
#define IDC_OPTIM_MD 20066
#define IDC_MC_DOCK_DONT_CALC_ENE 20067
#define IDC_MC_DOCK_SAVE_GIF 20068
#define IDC_MC_DOCK_SAVE_PICT 20069
#define IDC_MC_DOCK_PAUSE 20070
#define IDC_MC_DOCK_RESUME 20071
#define IDC_MC_DOCK_STOP 20072
#define ID_TEXT_MC_TEMP 20073
#define IDC_MC_DOCK_TEMP 20074
#define ID_TEXT_NUM_STEPS 20075
#define IDC_MC_DOCK_NUM_STEPS 20076
#define ID_TEXT_ROT_SCALE_FACTOR 20077
#define IDC_MC_DOCK_ANG_SCALE 20078
#define ID_TEXT_TRANSL_SCALE_FACTOR 20079
#define IDC_MC_DOCK_TR_SCALE 20080
#define ID_TEXT_DELAY_TIME 20081
#define IDC_MC_DOCK_DELAY 20082
#define IDC_MC_DOCK_DISCR_MOVES 20083
#define ID_TEXT_SKIP_POINTS 20084
#define ID_TEXT_AT_THE_START 20085
#define IDC_MC_DOCK_SKIP_INIT 20086
#define ID_TEXT_BETWEEN 20087
#define IDC_MC_DOCK_SKIP_BETWEEN 20088
#define ID_TEXT_ATOMS_TO_TRACE 20089
#define IDC_MC_DOCK_TRACE_AT_REF 20090
#define IDC_MC_DOCK_TRACE_ATOMS 20091
wxSizer *inter_mol_mc_dock_page( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
