//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: ha_wx_ed.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_ha_wx_ed_H__
#define __WDR_ha_wx_ed_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "ha_wx_ed_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

#define ID_TEXT 12900
#define ID_PDB_TEXTCTRL 12901
#define ID_BROWSE_PDB 12902
#define ID_EV_TEXTCTRL 12903
#define ID_BROWSE_EV 12904
#define ID_PPJ_TEXTCTRL 12905
#define ID_BROWSE_PROJ 12906
#define ID_BACK_BUTTON 12907
#define ID_BUTTON_NEXT 12908
wxSizer *EssentialDynamicsDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDD_CLUSTER_ANAL 12909
wxSizer *cluster_anal_dlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define IDC_ED_CHOOSE_MD_TRAJ 12910
#define IDC_ED_MD_TRAJ_FILE 12911
#define IDC_ED_CHOOSE_ATGRP 12912
#define IDC_ED_ATGRP_TO_ANAL 12913
#define IDC_ED_CHOOSE_PLATO_TRAJ 12914
#define IDC_ED_TRAJ_FILE_PLATO 12915
#define IDC_ED_GEN_PLATO_TRAJ 12916
#define IDC_ED_PLATO_ANAL_TYPE 12917
#define IDC_ED_N_CLUST 12918
#define IDC_ED_N_EIG_VEC 12919
#define IDC_ED_N_TIME_PROJ 12920
#define IDC_ED_COMP_SIM_MATRIX 12921
#define IDC_ED_PLATO_INPUT_FILE 12922
#define IDC_ED_PLATO_RUN_FILE 12923
#define IDC_ED_SAVE_PLATO_INPUT 12924
#define IDC_ED_RUN_PLATO 12925
#define IDC_ED_CHOOSE_PLATO_OUTPUT 12926
#define IDC_ED_PLATO_OUTPUT_FILE 12927
#define IDC_ED_LOAD_PLATO_OUTPUT 12928
#define IDC_ED_EIGVEC_LIST 12929
#define IDC_ED_RUN_VEC_ANIMATION 12930
#define IDC_ED_STOP_VEC_ANIMATION 12931
#define IDC_ED_SHIFT_ALONG_VEC 12932
#define IDC_ED_SHIFT_VAL 12933
#define IDC_ED_PROJ_TRAJ 12934
#define IDC_ED_TIME_PROJ_FILE 12935
#define IDC_ED_TIME_PROJ_LIST 12936
#define IDC_ED_PLOT_TIME_PROJ 12937
#define IDC_ED_PLOT_PROJ_2_VS_1 12938
wxSizer *PlatoAnalysisPage( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

#define ID_MENU 12939
#define IDM_ED_TEST_GRAPH 12940
wxMenuBar *collect_crd_menu();

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
