//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: ha_wx_res_molflex.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_ha_wx_res_molflex_H__
#define __WDR_ha_wx_res_molflex_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "ha_wx_res_molflex_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>

// Declare window functions

const int IDMF_TEXT = 32000;
const int ID_TEXT = 32001;
const int ID_HBOND_CUTOFF_DIST = 32002;
const int ID_HB_MAX_ANGLE = 32003;
const int ID_PH_CUTOFF_DIST = 32004;
const int ID_FIND_HBOND_AND_PH = 32005;
const int ID_COMPUTE_DUTY_CYCLE = 32006;
const int ID_CHOOSE_MD_TRAJ = 32007;
const int ID_MD_TRAJ_NAME = 32008;
const int ID_HB_DUTY_CYCLE_CUTOFF = 32009;
const int ID_HB_ENERGY_CUTOFF = 32010;
const int ID_HPT_DUTY_CYCLE_CUTOFF = 32011;
const int ID_SAVE_FIRST_INPUT_FILES = 32012;
const int ID_RUN_FIRST = 32008;
const int ID_ATMGRP1_SELECT = 32013;
const int ID_ATMGRP2_SELECT = 32014;
const int ID_UPDATE_CHART = 32015;
const int ID_EDIT_GRPS = 32016;
const int ID_MD_STATS = 32017;
const int ID_HB_LIST = 32018;
const int ID_DEL_SELECT_HB = 32019;
const int ID_PH_LIST = 32020;
const int ID_DEL_SELECT_PH = 32021;
wxSizer *molFlexDlg( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
