//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: ha_wx_res_mikola.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_ha_wx_res_mikola_H__
#define __WDR_ha_wx_res_mikola_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "ha_wx_res_mikola_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>
#include <wx/tglbtn.h>
#include <wx/collpane.h>
#include <wx/hyperlink.h>
#include <wx/animate.h>
#include <wx/filepicker.h>
#include <wx/datectrl.h>
#include <wx/fontpicker.h>
#include <wx/clrpicker.h>
#include <wx/srchctrl.h>
#if wxCHECK_VERSION(2,9,0)
#include <wx/editlbox.h>
#endif

// Declare window functions

#define IDT_PYMOD 25000
wxSizer *PyModDialogFunc( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

#define ID_PV_TEXT 25001
#define IDSC_PV_LEVEL 25002
#define IDSC_PV_LEVEL2 25003
#define IDB_PV_CP1D1 25004
#define IDB_PV_CP1D2 25005
#define IDB_PV_CP2D 25006
#define IDS_PV_LEVEL 25007
#define IDT_PV_MIN 25008
#define IDT_PV_MAX 25009
#define IDC_PV_PLANE 25010
#define IDCB_PV_HIDEZERO 25011
#define IDCB_PV_HIDE 25012
wxSizer *wxPlaneViewOfHaField3DDlgF( wxWindow *parent, bool call_fit = true, bool set_sizer = true );

// Declare menubar functions

#define IDM_PYMOD_FILE 25013
#define IDM_PYMOD_CLEAR 25014
#define IDM_PYMOD_OPEN 25015
#define IDM_PYMOD_SAVE 25016
wxMenuBar *PyModMenuBarFunc();

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
