// generated by hashgen.py, using simple hash function
#ifndef MORT_COMMON_HASHCODE_HPP
#define MORT_COMMON_HASHCODE_HPP

#include <map>
#include <string>

namespace mort
{
    typedef long long hashid_t;
    using std::string;
    static const hashid_t AAPOS           = 47000000ULL;
    static const hashid_t ADDITION        = 2188132356920ULL;
    static const hashid_t ALLIPHAITIC     = 23194501875730040ULL;
    static const hashid_t ALONE           = 11094840ULL;
    static const hashid_t AMBER           = 43778080ULL;
    static const hashid_t AMBER6          = 3320578080ULL;
    static const hashid_t AMBERXYZ        = 4196702978080ULL;
    static const hashid_t AMOEBA          = 2838880ULL;
    static const hashid_t AND             = 5320ULL;
    static const hashid_t ANGL            = 714120ULL;
    static const hashid_t AROM            = 791080ULL;
    static const hashid_t AROMATIC        = 362394391080ULL;
    static const hashid_t ATOM            = 791160ULL;
    static const hashid_t ATOMPAIR        = 2818087191160ULL;
    static const hashid_t BALLSTICK       = 65898440401601ULL;
    static const hashid_t BISECTOR        = 2844575005121ULL;
    static const hashid_t BOND            = 213361ULL;
    static const hashid_t BONDI           = 20693361ULL;
    static const hashid_t BOX             = 37361ULL;
    static const hashid_t BRNR            = 1109481ULL;
    static const hashid_t CAP             = 24002ULL;
    static const hashid_t CHAIN           = 33792282ULL;
    static const hashid_t CHAINAME        = 704545792282ULL;
    static const hashid_t COLOR           = 44434162ULL;
    static const hashid_t COMMENT         = 79166227762ULL;
    static const hashid_t CONN1           = 69973362ULL;
    static const hashid_t CONN2           = 72533362ULL;
    static const hashid_t CONN3           = 75093362ULL;
    static const hashid_t CONST           = 49813362ULL;
    static const hashid_t CTERM           = 31815162ULL;
    static const hashid_t DEPTH           = 19160163ULL;
    static const hashid_t ELEMENT         = 79166214844ULL;
    static const hashid_t EQUIL           = 28704644ULL;
    static const hashid_t FCHG            = 395285ULL;
    static const hashid_t FIRST           = 49819525ULL;
    static const hashid_t FORCE           = 10395765ULL;
    static const hashid_t FRCMOD          = 343811885ULL;
    static const hashid_t GBE             = 6446ULL;
    static const hashid_t GBFS            = 1160046ULL;
    static const hashid_t HASHMAP         = 61471196807ULL;
    static const hashid_t HEAD            = 192167ULL;
    static const hashid_t HELIX           = 59409767ULL;
    static const hashid_t HYBRID          = 328770567ULL;
    static const hashid_t ID              = 128ULL;
    static const hashid_t INDEX           = 59141328ULL;
    static const hashid_t INPCRD          = 350872528ULL;
    static const hashid_t KNOWN           = 34710930ULL;
    static const hashid_t LESCOPY         = 99875996971ULL;
    static const hashid_t LESTYPE         = 17982684971ULL;
    static const hashid_t LEVEL           = 28449771ULL;
    static const hashid_t LINE            = 277131ULL;
    static const hashid_t LOOP            = 982971ULL;
    static const hashid_t MASS            = 1180812ULL;
    static const hashid_t MBONDI          = 827734452ULL;
    static const hashid_t MBONDI2         = 115515734452ULL;
    static const hashid_t MDLNAME         = 17613649732ULL;
    static const hashid_t MOL2            = 1810172ULL;
    static const hashid_t MONO            = 917372ULL;
    static const hashid_t MUTABLE         = 17512991212ULL;
    static const hashid_t NAME            = 275213ULL;
    static const hashid_t NBRLIST         = 79688411253ULL;
    static const hashid_t NBRTYPE         = 17982683253ULL;
    static const hashid_t NORMAL          = 1127195773ULL;
    static const hashid_t NOT             = 30973ULL;
    static const hashid_t NTERM           = 31815173ULL;
    static const hashid_t OCT             = 30494ULL;
    static const hashid_t OFF             = 8214ULL;
    static const hashid_t OFF3            = 1864214ULL;
    static const hashid_t ON              = 534ULL;
    static const hashid_t ONLY            = 1554134ULL;
    static const hashid_t OOPS            = 1176574ULL;
    static const hashid_t OPBEND          = 340738214ULL;
    static const hashid_t OPTIONAL        = 1803607583014ULL;
    static const hashid_t OR              = 694ULL;
    static const hashid_t ORDER           = 43781494ULL;
    static const hashid_t OTHER           = 43787974ULL;
    static const hashid_t PATTERN         = 55000286415ULL;
    static const hashid_t PCHG            = 395295ULL;
    static const hashid_t PDB             = 1735ULL;
    static const hashid_t PERIOD          = 343579375ULL;
    static const hashid_t PITORS          = 1887646735ULL;
    static const hashid_t PLANE           = 11072455ULL;
    static const hashid_t POLAR           = 43538175ULL;
    static const hashid_t POLE            = 274175ULL;
    static const hashid_t POLTYPE         = 17982674175ULL;
    static const hashid_t POLTYPEID       = 20989502674175ULL;
    static const hashid_t POSITION        = 2188132381375ULL;
    static const hashid_t PRMTOP          = 1573075895ULL;
    static const hashid_t PTOR            = 1111175ULL;
    static const hashid_t REDUCT          = 1952004977ULL;
    static const hashid_t REQUIRED        = 509666585777ULL;
    static const hashid_t RESD            = 220977ULL;
    static const hashid_t RESID           = 8220977ULL;
    static const hashid_t RESNAME         = 17613660977ULL;
    static const hashid_t RING            = 405137ULL;
    static const hashid_t RSTAR           = 43551137ULL;
    static const hashid_t SCEE            = 262498ULL;
    static const hashid_t SCNB            = 84898ULL;
    static const hashid_t SDF             = 8138ULL;
    static const hashid_t SECOND          = 341379378ULL;
    static const hashid_t SELECTED        = 509854993778ULL;
    static const hashid_t SEQUENCE        = 664894745778ULL;
    static const hashid_t SHEET           = 48902698ULL;
    static const hashid_t SHELL           = 28870698ULL;
    static const hashid_t SMARTS          = 1892928498ULL;
    static const hashid_t SMILES          = 1854157298ULL;
    static const hashid_t SOLUTE          = 459538178ULL;
    static const hashid_t SOLUTE_NATOM    = 5184948453835538178ULL;
    static const hashid_t SOLUTE_NRESD    = 1448197145035538178ULL;
    static const hashid_t SOLVENT_TYPE    = 1841429951806802178ULL;
    static const hashid_t SOLVENT_INFO    = 5927920678206802178ULL;
    static const hashid_t STEREO          = 1444935178ULL;
    static const hashid_t STICK           = 25741578ULL;
    static const hashid_t STRBND          = 340571978ULL;
    static const hashid_t STRBNDID        = 524628571978ULL;
    static const hashid_t SYMBOL          = 1162324178ULL;
    static const hashid_t TAIL            = 716819ULL;
    static const hashid_t TINKERXYZ       = 167868119701139ULL;
    static const hashid_t TOR2            = 1819779ULL;
    static const hashid_t TOR2FUNC        = 382990619779ULL;
    static const hashid_t TORID           = 8219779ULL;
    static const hashid_t TORS            = 1179779ULL;
    static const hashid_t TRANSMAT        = 3114235712699ULL;
    static const hashid_t TRANSPOS        = 3008046912699ULL;
    static const hashid_t TREE            = 263099ULL;
    static const hashid_t TYPE            = 280979ULL;
    static const hashid_t TYPEID          = 327960979ULL;
    static const hashid_t UREY            = 1543100ULL;
    static const hashid_t UREYID          = 329223100ULL;
    static const hashid_t VBUFF           = 13152061ULL;
    static const hashid_t VDWR            = 1123341ULL;
    static const hashid_t VDWTYPE         = 17982691341ULL;
    static const hashid_t VECTOR          = 1777859381ULL;
    static const hashid_t VELOCITY        = 4010809233781ULL;
    static const hashid_t VISIBLE         = 17513501141ULL;
    static const hashid_t WEIGHT          = 1963916982ULL;
    static const hashid_t WGTDIFF         = 21012702662ULL;

    string unhash(const hashid_t& id);
    hashid_t hash(const string& name);

} // namespace mort

#endif


