{% set version = "21.02.20" %}

package:
  name: harlem
  version: {{ version }}

source:
  path: ../basis
  path: ../HARLEM/molset
  path: ../HARLEM/linux
  
requirements:
  build:
    - python
    - setuptools
    
  run:
    - python
    - pip    
  


