{% set version = "21.02.20" %}

package:
  name: harlem
  version: {{ version }}

source:
  path: ../../MOLSET_SHARED_LIBS
  
requirements:
  build:
    - python
    - setuptools
    
  run:
    - python
    - pip    
  


