{% set version = "21.03.19" %}

package:
  name: harlem
  version: {{ version }}

source:
  path: ../../MOLSET_BIN_LIBS
  
requirements:
  build:
    - python
    - setuptools
    
  run:
    - python
    - pip    
  


