######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 13 22:55:14 2006
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ..
CONFIG += staticlib

# Input
HEADERS += octree.hpp solvate.hpp
SOURCES += addions.cpp octree.cpp solvate.cpp
