from molset import *
mset = MolSet()
mset.LoadPDBFile("6PTI.pdb")
medit = MolEditor()
medit.AddMissingAtoms(mset)
mm_mod = mset.GetMolMechMod(True)
mm_mod.InitMolMechModel(AMBER_10)
mm_model = mm_mod.GetMolMechModel()
mm_mod.SetMMExternalProg(PMEMD_18)
mm_mod.SetMMRunType(MD_RUN)
mm_mod.SetRunInternal(0)
mm_model.SetNBCutDist(9.0)
mm_mod.SetNumMDSteps(1000)
mm_mod.SetWrtRstrtFreq(100)
mm_mod.SetWrtMDTrajFreq(100)
mm_mod.SetWrtLogFreq(10)
mm_mod.p_amber_driver.SaveAllInpFiles()
mm_mod.Run()
