# -*- coding: UTF-8 -*-

#-----------------------------------------------------------------------------
# Python source generated by wxDesigner from file: pnpgui.wdr
# Do not modify this file, all changes will be lost!
#-----------------------------------------------------------------------------

# Include wxPython modules
import wx
import wx.grid

# Custom source
import wx
from wxextra.intctrl import IntCtrl
from wx.lib.masked import NumCtrl
import wxextra.filebrowsebutton as filebrowse

# Window functions

IDpnpNOTEBOOK = 27000

def pnpGUI( parent, call_fit = True, set_sizer = True ):
    item0 = wx.GridSizer( 0, 1, 0, 0 )
    
    item2 = wx.Notebook( parent, IDpnpNOTEBOOK, wx.DefaultPosition, [640,560], 0 )
    item1 = item2
    
    item3 = wx.Panel( item2, -1 )
    pnpPrep(item3, False)
    item2.AddPage( item3, "Atomic Parameters" )

    item4 = wx.Panel( item2, -1 )
    pnpMapCreation(item4, False)
    item2.AddPage( item4, "Maps Building" )

    item5 = wx.Panel( item2, -1 )
    pnpMapPatch(item5, False)
    item2.AddPage( item5, "Maps Patching" )

    item6 = wx.Panel( item2, -1 )
    pnpPBSR(item6, False)
    item2.AddPage( item6, "PB-SR" )

    item7 = wx.Panel( item2, -1 )
    pnpIAVRef(item7, False)
    item2.AddPage( item7, "IAV Refinement" )

    item8 = wx.Panel( item2, -1 )
    pnpPNPSR(item8, False)
    item2.AddPage( item8, "PNP-SR" )

    item0.Add( item1, 0, wx.GROW|wx.ALL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXT = 27001
IDCpnpFF4QRdiel = 27002
IDTCpnpAddRion1 = 27003
IDTCpnpAddRion2 = 27004
IDCpnpFF4SR = 27005
ID_LINE = 27006
IDBpnpSetParam = 27007
IDBpnpCalcStats = 27008
IDTCpnpAtmParFileName = 27009
IDBpnpSaveAtmPar = 27010
IDGpnpAtomParam = 27011

def pnpPrep( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Atomic Charges and Radii for Setting Internal  Dielectric Media" )
    item1 = wx.StaticBoxSizer( item2, wx.HORIZONTAL )
    
    item3 = wx.StaticText( parent, ID_TEXT, "Set Q and R using:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item1.Add( item3, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item4 = wx.Choice( parent, IDCpnpFF4QRdiel, wx.DefaultPosition, [100,-1], [], 0 )
    item1.Add( item4, 1, wx.ALIGN_CENTER, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6 = wx.StaticBox( parent, -1, "Atomic Ion Excluded Radius for Setting Initial Ion Accessible Volume" )
    item5 = wx.StaticBoxSizer( item6, wx.HORIZONTAL )
    
    item7 = wx.StaticText( parent, ID_TEXT, "Add Ion Radii :  ", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item7, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item8 = wx.StaticText( parent, ID_TEXT, "Ion1", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item8, 0, wx.ALIGN_CENTER, 5 )

    item9 = NumCtrl( parent, IDTCpnpAddRion1, "0.5", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=0,max=50,integerWidth=2,fractionWidth=2,groupDigits=False,signedForegroundColour="Black" )
    item5.Add( item9, 0, wx.ALIGN_CENTER, 5 )

    item10 = wx.StaticText( parent, ID_TEXT, "Angstroms", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item10, 0, wx.ALIGN_CENTER, 5 )

    item11 = wx.StaticText( parent, ID_TEXT, "Ion2", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item11, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item12 = NumCtrl( parent, IDTCpnpAddRion2, "0.5", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=0,max=50,integerWidth=2,fractionWidth=2,groupDigits=False,signedForegroundColour="Black" )
    item5.Add( item12, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item13 = wx.StaticText( parent, ID_TEXT, "Angstroms", wx.DefaultPosition, wx.DefaultSize, 0 )
    item5.Add( item13, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item15 = wx.StaticBox( parent, -1, "Atomic Soft Repulsion Parameters" )
    item14 = wx.StaticBoxSizer( item15, wx.HORIZONTAL )
    
    item16 = wx.StaticText( parent, ID_TEXT, "Set Soft Repulsion Parameters using:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item16, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item17 = wx.Choice( parent, IDCpnpFF4SR, wx.DefaultPosition, [100,-1], [], 0 )
    item14.Add( item17, 1, wx.ALIGN_CENTER, 5 )

    item0.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item18 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item18, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item20 = wx.StaticBox( parent, -1, "Parameters" )
    item19 = wx.StaticBoxSizer( item20, wx.VERTICAL )
    
    item21 = wx.BoxSizer( wx.HORIZONTAL )
    
    item22 = wx.Button( parent, IDBpnpSetParam, "Set Parameters", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.Add( item22, 0, wx.ALIGN_CENTER, 5 )

    item23 = wx.Button( parent, IDBpnpCalcStats, "Calc. Stats", wx.DefaultPosition, wx.DefaultSize, 0 )
    item23.SetToolTip( wx.ToolTip("Calculate total charge, coordinates min max and some other properties") )
    item21.Add( item23, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item24 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpAtmParFileName, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Atomic Parameters File:",fileMask="*.atmpar",initialValue="S0_system.atmpar",history=["S0_system.atmpar"],fileMode=wx.FD_SAVE )
    item21.Add( item24, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item25 = wx.Button( parent, IDBpnpSaveAtmPar, "Save Again", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.Add( item25, 0, wx.ALIGN_CENTER, 5 )

    item19.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item26 = wx.grid.Grid( parent, IDGpnpAtomParam, wx.DefaultPosition, [200,160], wx.WANTS_CHARS )
    item19.Add( item26, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item19, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

IDTCpnpPNPSR_SysTopFileNameIN = 27012
IDTCpnpPNPSR_DiffFileNameIN = 27013
IDTCpnpPNPSR_SRFileName = 27014
IDTCpnpPNPSR_PotFileNameIN = 27015
IDTCpnpPNPSR_ConcFileNameIN = 27016
IDRpnpPNPSR_AppPotMode_AloneMem = 27017
IDTpnpPNPSR_AppPotMode_AloneMem1 = 27018
IDTpnpPNPSR_PotDiff = 27019
IDTpnpPNPSR_AppPotMode_AloneMem2 = 27020
IDRpnpPNPSR_AppPotMode_Manual = 27021
IDTpnpPNPSR_AppPotMode_Manual1 = 27022
IDTpnpPNPSR_z0 = 27023
IDTpnpPNPSR_AppPotMode_Manual2 = 27024
IDTpnpPNPSR_z1 = 27025
IDTpnpPNPSR_AppPotMode_Manual3 = 27026
IDTpnpPNPSR_Pot0 = 27027
IDTpnpPNPSR_AppPotMode_Manual4 = 27028
IDTpnpPNPSR_Pot1 = 27029
IDTpnpPNPSR_AppPotMode_Manual5 = 27030
IDTpnpPNPSR_MaxPNPCylces = 27031
IDTpnpPNPSR_CurrentTolerance = 27032
IDTpnpPNPSR_PS_Niter = 27033
IDTpnpPNPSR_PS_Relax = 27034
IDTpnpPNPSR_NPS_Niter = 27035
IDTpnpPNPSR_NPS_Relax = 27036
IDTCpnpPNPSR_PotFileNameOUT = 27037
IDTCpnpPNPSR_ConcFileNameOUT = 27038
ID_TEXTCTRL = 27039
IDBpnpPNPSR_Run = 27040
IDBpnpPNPSR_ViewPot = 27041
IDBpnpPNPSR_ViewConc = 27042

def pnpPNPSR( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Input Files" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.BoxSizer( wx.HORIZONTAL )
    
    item4 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpPNPSR_SysTopFileNameIN, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="System Topology:",fileMask="*.systop",initialValue="S3_IAVRefined_System.systop",history=["S3_IAVRefined_System.systop","S1_System_Patched.systop","S1_System.systop"],fileMode=wx.FD_OPEN )
    item3.Add( item4, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item5 = wx.BoxSizer( wx.HORIZONTAL )
    
    item6 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpPNPSR_DiffFileNameIN, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Diffusion:",fileMask="*.bin",initialValue="S3_IAVRefined_Diffusion.bin",history=["S3_IAVRefined_Diffusion.bin","S1_Diffusion_Patched.bin","S1_Diffusion.bin","None"],fileMode=wx.FD_OPEN )
    item5.Add( item6, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item1.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item7 = wx.BoxSizer( wx.VERTICAL )
    
    item8 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpPNPSR_SRFileName, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Soft Repultion:",fileMask="*.bin",initialValue="S1_SR.bin",history=["S1_SR.bin","None"],fileMode=wx.FD_OPEN )
    item7.Add( item8, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item1.Add( item7, 1, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item9 = wx.BoxSizer( wx.HORIZONTAL )
    
    item10 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpPNPSR_PotFileNameIN, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Electrostatic Potential (initial guess):",fileMask="*.bin",initialValue="S3_IAVRefined_Pot.bin",history=["S3_IAVRefined_Pot.bin","S2_PBSR_Pot.bin","None"],fileMode=wx.FD_OPEN )
    item9.Add( item10, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item1.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11 = wx.BoxSizer( wx.HORIZONTAL )
    
    item12 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpPNPSR_ConcFileNameIN, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Concentrations:",fileMask="*.bin",initialValue="S3_IAVRefined_Conc.bin",history=["S3_IAVRefined_Conc.bin","S2_PBSR_Conc.bin","None"],fileMode=wx.FD_OPEN )
    item11.Add( item12, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item1.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item14 = wx.StaticBox( parent, -1, "Applied Potential" )
    item13 = wx.StaticBoxSizer( item14, wx.VERTICAL )
    
    item15 = wx.BoxSizer( wx.HORIZONTAL )
    
    item16 = wx.RadioButton( parent, IDRpnpPNPSR_AppPotMode_AloneMem, "Apply Linear Drop Along Membrane", wx.DefaultPosition, wx.DefaultSize, wx.RB_GROUP )
    item16.SetValue( True )
    item15.Add( item16, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item15.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item17 = wx.StaticText( parent, IDTpnpPNPSR_AppPotMode_AloneMem1, "Potential Diffrence", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.Add( item17, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item18 = NumCtrl( parent, IDTpnpPNPSR_PotDiff, "80.0", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=-8000,max=8000,integerWidth=5,fractionWidth=2,groupDigits=False,signedForegroundColour="Black" )
    item15.Add( item18, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item19 = wx.StaticText( parent, IDTpnpPNPSR_AppPotMode_AloneMem2, "mV", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.Add( item19, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item13.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item20 = wx.BoxSizer( wx.HORIZONTAL )
    
    item21 = wx.RadioButton( parent, IDRpnpPNPSR_AppPotMode_Manual, "Select Linear Drop Manually", wx.DefaultPosition, wx.DefaultSize, 0 )
    item20.Add( item21, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item22 = wx.StaticText( parent, IDTpnpPNPSR_AppPotMode_Manual1, "z0:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item20.Add( item22, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item23 = NumCtrl( parent, IDTpnpPNPSR_z0, "-45.0", wx.DefaultPosition, [40,-1], 0|wx.TE_RIGHT, min=-8000,max=8000,integerWidth=5,fractionWidth=2,groupDigits=False,signedForegroundColour="Black" )
    item20.Add( item23, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item24 = wx.StaticText( parent, IDTpnpPNPSR_AppPotMode_Manual2, "Ang.  z1:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item20.Add( item24, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item25 = NumCtrl( parent, IDTpnpPNPSR_z1, "-17", wx.DefaultPosition, [40,-1], 0|wx.TE_RIGHT, min=-8000,max=8000,integerWidth=5,fractionWidth=2,groupDigits=False,signedForegroundColour="Black" )
    item20.Add( item25, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item26 = wx.StaticText( parent, IDTpnpPNPSR_AppPotMode_Manual3, "Ang.  Phi0:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item20.Add( item26, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item27 = NumCtrl( parent, IDTpnpPNPSR_Pot0, "80.0", wx.DefaultPosition, [40,-1], 0|wx.TE_RIGHT, min=-8000,max=8000,integerWidth=5,fractionWidth=2,groupDigits=False,signedForegroundColour="Black" )
    item20.Add( item27, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item28 = wx.StaticText( parent, IDTpnpPNPSR_AppPotMode_Manual4, "mV  Phi1", wx.DefaultPosition, wx.DefaultSize, 0 )
    item20.Add( item28, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item29 = NumCtrl( parent, IDTpnpPNPSR_Pot1, "0.0", wx.DefaultPosition, [40,-1], 0|wx.TE_RIGHT, min=-8000,max=8000,integerWidth=5,fractionWidth=2,groupDigits=False,signedForegroundColour="Black" )
    item20.Add( item29, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item30 = wx.StaticText( parent, IDTpnpPNPSR_AppPotMode_Manual5, "mV", wx.DefaultPosition, wx.DefaultSize, 0 )
    item20.Add( item30, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item13.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item32 = wx.StaticBox( parent, -1, "Solver Parameters" )
    item31 = wx.StaticBoxSizer( item32, wx.VERTICAL )
    
    item33 = wx.BoxSizer( wx.HORIZONTAL )
    
    item34 = wx.StaticText( parent, ID_TEXT, "Max. PNP Cycles", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item34, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item35 = NumCtrl( parent, IDTpnpPNPSR_MaxPNPCylces, "1000", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=1,max=99999,integerWidth=5,fractionWidth=0,groupDigits=False )
    item33.Add( item35, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item33.Add( [ 20, 20 ] , 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item36 = wx.StaticText( parent, ID_TEXT, "Current Tolerance", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item36, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item37 = wx.TextCtrl( parent, IDTpnpPNPSR_CurrentTolerance, "0.0", wx.DefaultPosition, [80,-1], 0 )
    item33.Add( item37, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item38 = wx.StaticText( parent, ID_TEXT, "pA", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.Add( item38, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item31.Add( item33, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item39 = wx.BoxSizer( wx.HORIZONTAL )
    
    item40 = wx.StaticText( parent, ID_TEXT, "PE Iterations:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item39.Add( item40, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item41 = NumCtrl( parent, IDTpnpPNPSR_PS_Niter, "20", wx.DefaultPosition, [40,-1], 0|wx.TE_RIGHT, min=1,max=99999,integerWidth=5,fractionWidth=0,groupDigits=False )
    item39.Add( item41, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item42 = wx.StaticText( parent, ID_TEXT, "PE Relaxation:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item39.Add( item42, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item43 = NumCtrl( parent, IDTpnpPNPSR_PS_Relax, "1.5", wx.DefaultPosition, [40,-1], 0|wx.TE_RIGHT, min=0.0001,max=1.9999,integerWidth=1,fractionWidth=4,groupDigits=False )
    item39.Add( item43, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item44 = wx.StaticText( parent, ID_TEXT, "NPE Iterations:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item39.Add( item44, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item45 = NumCtrl( parent, IDTpnpPNPSR_NPS_Niter, "20", wx.DefaultPosition, [40,-1], 0|wx.TE_RIGHT, min=1,max=99999,integerWidth=5,fractionWidth=0,groupDigits=False )
    item39.Add( item45, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item46 = wx.StaticText( parent, ID_TEXT, "NPE Relaxation:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item39.Add( item46, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item47 = NumCtrl( parent, IDTpnpPNPSR_NPS_Relax, "1.5", wx.DefaultPosition, [40,-1], 0|wx.TE_RIGHT, min=0.0001,max=1.9999,integerWidth=1,fractionWidth=4,groupDigits=False )
    item39.Add( item47, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item31.Add( item39, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item31, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item49 = wx.StaticBox( parent, -1, "Output Files" )
    item48 = wx.StaticBoxSizer( item49, wx.VERTICAL )
    
    item50 = wx.BoxSizer( wx.HORIZONTAL )
    
    item51 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpPNPSR_PotFileNameOUT, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Electrostatic Potential:",fileMask="*.bin",initialValue="S4_PNPSR_Pot.bin",history=["S4_PNPSR_Pot.bin"],fileMode=wx.FD_SAVE )
    item50.Add( item51, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item48.Add( item50, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item52 = wx.BoxSizer( wx.HORIZONTAL )
    
    item53 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpPNPSR_ConcFileNameOUT, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Concentrations:",fileMask="*.bin",initialValue="S4_PNPSR_Conc.bin",history=["S4_PNPSR_Conc.bin"],fileMode=wx.FD_SAVE )
    item52.Add( item53, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item48.Add( item52, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item48, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item55 = wx.StaticBox( parent, -1, "Run Control and Results" )
    item54 = wx.StaticBoxSizer( item55, wx.HORIZONTAL )
    
    item56 = wx.BoxSizer( wx.VERTICAL )
    
    item56.Add( [ 25, 25 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item57 = wx.StaticText( parent, ID_TEXT, "Current, pA", wx.DefaultPosition, wx.DefaultSize, 0 )
    item56.Add( item57, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item58 = wx.StaticText( parent, ID_TEXT, "Std.Dev., pA", wx.DefaultPosition, wx.DefaultSize, 0 )
    item56.Add( item58, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item54.Add( item56, 0, wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item59 = wx.BoxSizer( wx.VERTICAL )
    
    item60 = wx.StaticText( parent, ID_TEXT, "Total", wx.DefaultPosition, wx.DefaultSize, 0 )
    item59.Add( item60, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item61 = wx.TextCtrl( parent, ID_TEXTCTRL, "20.58", wx.DefaultPosition, [80,-1], 0 )
    item59.Add( item61, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item62 = wx.TextCtrl( parent, ID_TEXTCTRL, "5.8E-04", wx.DefaultPosition, [80,-1], 0 )
    item59.Add( item62, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item54.Add( item59, 1, wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item63 = wx.BoxSizer( wx.VERTICAL )
    
    item64 = wx.StaticText( parent, ID_TEXT, "Ions0", wx.DefaultPosition, wx.DefaultSize, 0 )
    item63.Add( item64, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item65 = wx.TextCtrl( parent, ID_TEXTCTRL, "3.92", wx.DefaultPosition, [80,-1], 0 )
    item63.Add( item65, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item66 = wx.TextCtrl( parent, ID_TEXTCTRL, "1.3E-04", wx.DefaultPosition, [80,-1], 0 )
    item63.Add( item66, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item54.Add( item63, 1, wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item67 = wx.BoxSizer( wx.VERTICAL )
    
    item68 = wx.StaticText( parent, ID_TEXT, "Ions2", wx.DefaultPosition, wx.DefaultSize, 0 )
    item67.Add( item68, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item69 = wx.TextCtrl( parent, ID_TEXTCTRL, "16.65", wx.DefaultPosition, [80,-1], 0 )
    item67.Add( item69, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item70 = wx.TextCtrl( parent, ID_TEXTCTRL, "4.5E-04", wx.DefaultPosition, [80,-1], 0 )
    item67.Add( item70, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item54.Add( item67, 1, wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item54.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item71 = wx.BoxSizer( wx.VERTICAL )
    
    item72 = wx.Button( parent, IDBpnpPNPSR_Run, "Run PNP-SR", wx.DefaultPosition, wx.DefaultSize, 0 )
    item71.Add( item72, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item73 = wx.Button( parent, IDBpnpPNPSR_ViewPot, "View Potential", wx.DefaultPosition, wx.DefaultSize, 0 )
    item71.Add( item73, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item74 = wx.Button( parent, IDBpnpPNPSR_ViewConc, "View Concentrations", wx.DefaultPosition, wx.DefaultSize, 0 )
    item71.Add( item74, 0, wx.ALIGN_CENTER, 5 )

    item54.Add( item71, 0, wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item0.Add( item54, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_TEXTPNP = 27043
IDCpnpGridSizeX = 27044
IDCpnpGridSizeY = 27045
IDCpnpGridSizeZ = 27046
IDCpnpGridScale = 27047
IDBpnpDrawSimBox = 27048
IDTCpnpIonsQ1 = 27049
IDTCpnpIonsQ2 = 27050
IDTCpnpIonsDbulk1 = 27051
IDTCpnpIonsDbulk2 = 27052
IDTCpnpIonsCbulk = 27053
IDTCpnpIonsR1 = 27054
IDTCpnpIonsR2 = 27055
IDTCpnpSolDiel = 27056
IDFBBpnpCrMapAtomParFile = 27057
IDTCpnpProtDiel = 27058
IDTCpnpMemDiel = 27059
IDBpnpDrawMem = 27060
IDTCpnpMemZ1 = 27061
IDTCpnpMemZ2 = 27062
IDTCpnpMemX = 27063
IDTCpnpMemY = 27064
IDTCpnpMemR1 = 27065
IDRB_InitDiffMod = 27066
IDTCpnpRprobeDiel = 27067
IDTCpnpRprobeDiff = 27068
IDTCpnpScriptFileName = 27069
IDTCpnpSysTopFileNameOut = 27070
IDTCpnpDiffFileNameOut = 27071
IDTCpnpSRFileNameOut = 27072
IDBpnpSaveScript = 27073
IDBpnpRunScript = 27074
IDBpnpInterruptScript = 27075
IDBpnpStopScript = 27076
IDBpnpViewStaticCharge = 27077
IDBpnpViewDiel = 27078
IDBpnpViewSR = 27079
IDBpnpViewPlainDiff = 27080
IDBpnpViewDiff = 27081

def pnpMapCreation( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Grid Parameters" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.BoxSizer( wx.HORIZONTAL )
    
    item4 = wx.StaticText( parent, ID_TEXTPNP, "Grid Size:  ", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.RIGHT, 0 )

    item5 = NumCtrl( parent, IDCpnpGridSizeX, "121", wx.DefaultPosition, wx.DefaultSize, wx.TE_PROCESS_TAB|wx.TE_RIGHT, min=3,max=1026,integerWidth=4,fractionWidth=0,groupDigits=False )
    item5.SetToolTip( wx.ToolTip("in Grids") )
    item3.Add( item5, 1, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item6 = NumCtrl( parent, IDCpnpGridSizeY, "121", wx.DefaultPosition, wx.DefaultSize, wx.TE_PROCESS_TAB|wx.TE_RIGHT, min=3,max=1026,integerWidth=4,fractionWidth=0,groupDigits=False )
    item6.SetToolTip( wx.ToolTip("in Grids") )
    item3.Add( item6, 1, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item7 = NumCtrl( parent, IDCpnpGridSizeZ, "121", wx.DefaultPosition, wx.DefaultSize, wx.TE_PROCESS_TAB|wx.TE_RIGHT, min=3,max=1026,integerWidth=4,fractionWidth=0,groupDigits=False )
    item7.SetToolTip( wx.ToolTip("in Grids") )
    item3.Add( item7, 1, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item8 = wx.StaticText( parent, ID_TEXTPNP, "  Grid Scale:  ", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item8, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 0 )

    item9 = NumCtrl( parent, IDCpnpGridScale, "2.0", wx.DefaultPosition, wx.DefaultSize, wx.TE_PROCESS_TAB|wx.TE_RIGHT, min=0.01,max=100.0,integerWidth=4,fractionWidth=2,groupDigits=False )
    item9.SetToolTip( wx.ToolTip("in Grids/Angstroms") )
    item3.Add( item9, 1, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item10 = wx.Button( parent, IDBpnpDrawSimBox, "Draw Simulation Box", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.SetToolTip( wx.ToolTip("Draw Simulation Box") )
    item3.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 0 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item12 = wx.StaticBox( parent, -1, "Ions Parameters" )
    item11 = wx.StaticBoxSizer( item12, wx.VERTICAL )
    
    item13 = wx.BoxSizer( wx.HORIZONTAL )
    
    item14 = wx.StaticText( parent, ID_TEXT, "Q1:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item14, 0, wx.ALIGN_CENTER, 5 )

    item15 = NumCtrl( parent, IDTCpnpIonsQ1, "1", wx.DefaultPosition, [80,-1], wx.TE_PROCESS_TAB|wx.TE_RIGHT, min=-8,max=8,integerWidth=1,fractionWidth=0,groupDigits=False,signedForegroundColour="Black" )
    item15.SetToolTip( wx.ToolTip("Charge of mobile ion of type 1, [e]") )
    item13.Add( item15, 0, wx.ALIGN_CENTER, 5 )

    item16 = wx.StaticText( parent, ID_TEXT, "Q2:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item16, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item17 = NumCtrl( parent, IDTCpnpIonsQ2, "-1", wx.DefaultPosition, [80,-1], wx.TE_PROCESS_TAB|wx.TE_RIGHT, min=-8,max=8,integerWidth=1,fractionWidth=0,groupDigits=False,signedForegroundColour="Black" )
    item17.SetToolTip( wx.ToolTip("Charge of mobile ion of type 1, [-e]") )
    item13.Add( item17, 0, wx.ALIGN_CENTER, 5 )

    item18 = wx.StaticText( parent, ID_TEXT, "Dbulk1:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item18, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item19 = NumCtrl( parent, IDTCpnpIonsDbulk1, "19.57", wx.DefaultPosition, [80,-1], wx.TE_PROCESS_TAB|wx.TE_RIGHT, min=0.01,max=100.0,integerWidth=3,fractionWidth=2,groupDigits=False )
    item19.SetToolTip( wx.ToolTip("Charge of diffusion coefficient of ion of type 1 in the bulk, [?]") )
    item13.Add( item19, 0, wx.ALIGN_CENTER, 5 )

    item20 = wx.StaticText( parent, ID_TEXT, "Dbulk2:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item20, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item21 = NumCtrl( parent, IDTCpnpIonsDbulk2, "20.32", wx.DefaultPosition, [80,-1], wx.TE_PROCESS_TAB|wx.TE_RIGHT, min=0.01,max=100.0,integerWidth=3,fractionWidth=2,groupDigits=False )
    item21.SetToolTip( wx.ToolTip("Charge of diffusion coefficient of ion of type 2 in the bulk, [?]") )
    item13.Add( item21, 0, wx.ALIGN_CENTER, 5 )

    item22 = wx.StaticText( parent, ID_TEXT, "Cbulk:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item22, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item23 = NumCtrl( parent, IDTCpnpIonsCbulk, "1.0", wx.DefaultPosition, [80,-1], wx.TE_PROCESS_TAB|wx.TE_RIGHT, min=0.001,max=90.0,integerWidth=2,fractionWidth=3,groupDigits=False )
    item23.SetToolTip( wx.ToolTip("Concentration of mobile ions in bulk, [M]") )
    item13.Add( item23, 0, wx.ALIGN_CENTER, 5 )

    item24 = wx.StaticText( parent, ID_TEXT, "Rion1:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item24, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item25 = NumCtrl( parent, IDTCpnpIonsR1, "2", wx.DefaultPosition, [80,-1], wx.TE_PROCESS_TAB|wx.TE_RIGHT, min=0,max=50,integerWidth=2,fractionWidth=2,groupDigits=False,signedForegroundColour="Black" )
    item25.SetToolTip( wx.ToolTip("Radius of mobile ion, only used for determination of IAV around implicit membrane") )
    item13.Add( item25, 0, wx.ALIGN_CENTER, 5 )

    item26 = wx.StaticText( parent, ID_TEXT, "Rion2:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item13.Add( item26, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item27 = NumCtrl( parent, IDTCpnpIonsR2, "2", wx.DefaultPosition, [80,-1], wx.TE_PROCESS_TAB|wx.TE_RIGHT, min=0,max=50,integerWidth=2,fractionWidth=2,groupDigits=False,signedForegroundColour="Black" )
    item27.SetToolTip( wx.ToolTip("Radius of mobile ion, only used for determination of IAV around implicit membrane") )
    item13.Add( item27, 0, wx.ALIGN_CENTER, 5 )

    item11.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item29 = wx.StaticBox( parent, -1, "Solvent Parameters" )
    item28 = wx.StaticBoxSizer( item29, wx.HORIZONTAL )
    
    item30 = wx.BoxSizer( wx.HORIZONTAL )
    
    item31 = wx.StaticText( parent, ID_TEXT, "Dielectric Constant:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item30.Add( item31, 0, wx.ALIGN_CENTER, 5 )

    item32 = NumCtrl( parent, IDTCpnpSolDiel, "80", wx.DefaultPosition, [80,-1], wx.TE_PROCESS_TAB|wx.TE_RIGHT, min=1.00,max=1000.0,integerWidth=4,fractionWidth=2,groupDigits=False )
    item32.SetToolTip( wx.ToolTip("Dielectric constant of solvent") )
    item30.Add( item32, 0, wx.ALIGN_CENTER, 5 )

    item28.Add( item30, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item28, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item34 = wx.StaticBox( parent, -1, "Protein Parameters" )
    item33 = wx.StaticBoxSizer( item34, wx.VERTICAL )
    
    item35 = wx.BoxSizer( wx.HORIZONTAL )
    
    item36 = filebrowse.FileBrowseButtonWithHistory( parent, IDFBBpnpCrMapAtomParFile, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Atomic Parameters File:",fileMask="*.atmpar",initialValue="S0_system.atmpar",history=["S0_system.atmpar","None"],fileMode=wx.FD_OPEN )
    item35.Add( item36, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item35.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER, 5 )

    item37 = wx.StaticText( parent, ID_TEXT, "Dielectric Constant:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item35.Add( item37, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item38 = NumCtrl( parent, IDTCpnpProtDiel, "4", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=1.00,max=1000.0,integerWidth=4,fractionWidth=2,groupDigits=False )
    item38.SetToolTip( wx.ToolTip("Dielectric Constant of Protein") )
    item35.Add( item38, 0, wx.ALIGN_CENTER, 5 )

    item33.Add( item35, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item33, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item40 = wx.StaticBox( parent, -1, "Membrane Model: Slab with Cyllindrical Hole" )
    item39 = wx.StaticBoxSizer( item40, wx.VERTICAL )
    
    item41 = wx.BoxSizer( wx.HORIZONTAL )
    
    item42 = wx.StaticText( parent, ID_TEXT, "Dielectric Constant:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item41.Add( item42, 0, wx.ALIGN_CENTER, 5 )

    item43 = NumCtrl( parent, IDTCpnpMemDiel, "2", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=1.00,max=1000.0,integerWidth=4,fractionWidth=2,groupDigits=False )
    item43.SetToolTip( wx.ToolTip("Membrane dielectric constant") )
    item41.Add( item43, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item41.Add( [ 20, 20 ] , 1, wx.ALIGN_CENTER, 5 )

    item44 = wx.Button( parent, IDBpnpDrawMem, "Draw Membrane", wx.DefaultPosition, wx.DefaultSize, 0 )
    item41.Add( item44, 0, wx.ALIGN_CENTER, 5 )

    item39.Add( item41, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item45 = wx.BoxSizer( wx.HORIZONTAL )
    
    item46 = wx.StaticText( parent, ID_TEXTPNP, "Membrane Starts at Z:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item45.Add( item46, 0, wx.ALIGN_CENTER, 5 )

    item47 = NumCtrl( parent, IDTCpnpMemZ1, "-14", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=-8000,max=8000,integerWidth=5,fractionWidth=2,groupDigits=False,signedForegroundColour="Black" )
    item45.Add( item47, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item48 = wx.StaticText( parent, ID_TEXTPNP, "Membrane Ends at Z:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item45.Add( item48, 0, wx.ALIGN_CENTER, 5 )

    item49 = NumCtrl( parent, IDTCpnpMemZ2, "14", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=-8000,max=8000,integerWidth=5,fractionWidth=2,groupDigits=False,signedForegroundColour="Black" )
    item45.Add( item49, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item39.Add( item45, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item50 = wx.BoxSizer( wx.HORIZONTAL )
    
    item51 = wx.StaticText( parent, ID_TEXTPNP, "Coordinate of the Hole X:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item50.Add( item51, 0, wx.ALIGN_CENTER, 5 )

    item52 = NumCtrl( parent, IDTCpnpMemX, "0", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=-8000,max=8000,integerWidth=5,fractionWidth=2,groupDigits=False,signedForegroundColour="Black" )
    item50.Add( item52, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item53 = wx.StaticText( parent, ID_TEXTPNP, "Y:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item50.Add( item53, 0, wx.ALIGN_CENTER, 5 )

    item54 = NumCtrl( parent, IDTCpnpMemY, "0", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=-8000,max=8000,integerWidth=5,fractionWidth=2,groupDigits=False,signedForegroundColour="Black" )
    item50.Add( item54, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item55 = wx.StaticText( parent, ID_TEXTPNP, "Radius of the Hole", wx.DefaultPosition, wx.DefaultSize, 0 )
    item50.Add( item55, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item56 = NumCtrl( parent, IDTCpnpMemR1, "15", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=0,max=8000,integerWidth=5,fractionWidth=2,groupDigits=False,signedForegroundColour="Black" )
    item50.Add( item56, 0, wx.ALIGN_CENTER, 5 )

    item39.Add( item50, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 0 )

    item0.Add( item39, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item57 = wx.BoxSizer( wx.HORIZONTAL )
    
    item58 = wx.RadioBox( parent, IDRB_InitDiffMod, "Initial Diffusion Model", wx.DefaultPosition, wx.DefaultSize, 
        ["Plain","MD"] , 1, wx.NO_BORDER|wx.RA_SPECIFY_ROWS )
    item58.SetToolTip( wx.ToolTip("Plain - bulk diffusion throughout IAV; MD - hyperbolic leveling to bulk value") )
    item57.Add( item58, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item60 = wx.StaticBox( parent, -1, "Other Parameters" )
    item59 = wx.StaticBoxSizer( item60, wx.VERTICAL )
    
    item61 = wx.BoxSizer( wx.HORIZONTAL )
    
    item62 = wx.StaticText( parent, ID_TEXTPNP, "Rprobe(For Dielectric Maps):", wx.DefaultPosition, wx.DefaultSize, 0 )
    item61.Add( item62, 0, wx.ALIGN_CENTER, 5 )

    item63 = NumCtrl( parent, IDTCpnpRprobeDiel, "1.4", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=-0,max=50,integerWidth=5,fractionWidth=2,groupDigits=False,signedForegroundColour="Black" )
    item63.SetToolTip( wx.ToolTip("Effective solvent radius for rolling around protein") )
    item61.Add( item63, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item64 = wx.StaticText( parent, ID_TEXTPNP, "Rprobe(For Diffusion Maps):", wx.DefaultPosition, wx.DefaultSize, 0 )
    item61.Add( item64, 0, wx.ALIGN_CENTER, 5 )

    item65 = NumCtrl( parent, IDTCpnpRprobeDiff, "0.5", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=0,max=50,integerWidth=5,fractionWidth=2,groupDigits=False,signedForegroundColour="Black" )
    item65.SetToolTip( wx.ToolTip("smothing of diffusion maps") )
    item61.Add( item65, 0, wx.ALIGN_CENTER|wx.LEFT|wx.RIGHT, 5 )

    item59.Add( item61, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item57.Add( item59, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item57, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item67 = wx.StaticBox( parent, -1, "Output Files" )
    item66 = wx.StaticBoxSizer( item67, wx.VERTICAL )
    
    item68 = wx.BoxSizer( wx.HORIZONTAL )
    
    item69 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpScriptFileName, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Script Filename:",fileMask="*.py",initialValue="S1_CreateMaps.py",history=["S1_CreateMaps.py"],fileMode=wx.FD_SAVE )
    item69.SetToolTip( wx.ToolTip("Script filename where maps creation instruction will be saved") )
    item68.Add( item69, 1, wx.ALIGN_CENTER, 5 )

    item70 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpSysTopFileNameOut, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="System Topology:",fileMask="*.systop",initialValue="S1_System.systop",history=["S1_System.systop"],fileMode=wx.FD_SAVE )
    item68.Add( item70, 1, wx.ALIGN_CENTER, 5 )

    item66.Add( item68, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 0 )

    item71 = wx.BoxSizer( wx.HORIZONTAL )
    
    item72 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpDiffFileNameOut, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Diffusion:",fileMask="*.bin",initialValue="S1_Diffusion.bin",history=["S1_Diffusion.bin","None"],fileMode=wx.FD_SAVE )
    item71.Add( item72, 1, wx.ALIGN_CENTER, 5 )

    item73 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpSRFileNameOut, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Soft Repultion:",fileMask="*.bin",initialValue="S1_SR.bin",history=["S1_SR.bin","None"],fileMode=wx.FD_SAVE )
    item71.Add( item73, 1, wx.ALIGN_CENTER, 5 )

    item66.Add( item71, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 0 )

    item0.Add( item66, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item74 = wx.BoxSizer( wx.HORIZONTAL )
    
    item76 = wx.StaticBox( parent, -1, "Run Control" )
    item75 = wx.StaticBoxSizer( item76, wx.VERTICAL )
    
    item77 = wx.BoxSizer( wx.HORIZONTAL )
    
    item78 = wx.Button( parent, IDBpnpSaveScript, "Save", wx.DefaultPosition, wx.DefaultSize, 0 )
    item78.SetToolTip( wx.ToolTip("Save Script") )
    item77.Add( item78, 0, wx.ALIGN_CENTER, 5 )

    item79 = wx.Button( parent, IDBpnpRunScript, "Save and Run", wx.DefaultPosition, wx.DefaultSize, 0 )
    item79.SetToolTip( wx.ToolTip("Save and Start Script Execution") )
    item77.Add( item79, 0, wx.ALIGN_CENTER, 5 )

    item75.Add( item77, 0, wx.ALIGN_CENTER, 5 )

    item80 = wx.BoxSizer( wx.HORIZONTAL )
    
    item81 = wx.Button( parent, IDBpnpInterruptScript, "Interrupt", wx.DefaultPosition, wx.DefaultSize, 0 )
    item81.SetToolTip( wx.ToolTip("interupt script execution") )
    item81.Enable(False)
    item80.Add( item81, 0, wx.ALIGN_CENTER, 5 )

    item82 = wx.Button( parent, IDBpnpStopScript, "Stop", wx.DefaultPosition, wx.DefaultSize, 0 )
    item82.SetToolTip( wx.ToolTip("Stop script execution") )
    item82.Enable(False)
    item80.Add( item82, 0, wx.ALIGN_CENTER, 5 )

    item75.Add( item80, 0, wx.ALIGN_CENTER, 5 )

    item74.Add( item75, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item84 = wx.StaticBox( parent, -1, "Results View" )
    item83 = wx.StaticBoxSizer( item84, wx.VERTICAL )
    
    item85 = wx.BoxSizer( wx.HORIZONTAL )
    
    item86 = wx.Button( parent, IDBpnpViewStaticCharge, "View Static Charge", wx.DefaultPosition, wx.DefaultSize, 0 )
    item85.Add( item86, 0, wx.ALIGN_CENTER, 5 )

    item87 = wx.Button( parent, IDBpnpViewDiel, "View Dielectric Constants", wx.DefaultPosition, wx.DefaultSize, 0 )
    item85.Add( item87, 0, wx.ALIGN_CENTER, 5 )

    item88 = wx.Button( parent, IDBpnpViewSR, "View Soft Repulsion", wx.DefaultPosition, wx.DefaultSize, 0 )
    item85.Add( item88, 0, wx.ALIGN_CENTER, 5 )

    item83.Add( item85, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item89 = wx.BoxSizer( wx.HORIZONTAL )
    
    item90 = wx.Button( parent, IDBpnpViewPlainDiff, "View Plain Diffusion", wx.DefaultPosition, wx.DefaultSize, 0 )
    item90.SetToolTip( wx.ToolTip("This eventially initial IAV") )
    item89.Add( item90, 0, wx.ALIGN_CENTER, 5 )

    item91 = wx.Button( parent, IDBpnpViewDiff, "View Diffusion", wx.DefaultPosition, wx.DefaultSize, 0 )
    item89.Add( item91, 0, wx.ALIGN_CENTER, 5 )

    item83.Add( item89, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item74.Add( item83, 1, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item0.Add( item74, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

IDTCpnpSysTopFileNameIn = 27082
IDTCpnpSRFileNameIn = 27083
IDTCpnpPBSR_Tolerance = 27084
IDTCpnpPBSR_Relax = 27085
IDTCpnpPBSR_Niter = 27086
IDTCpnpPotFileNameOut = 27087
IDTCpnpConcFileNameOut = 27088
IDBpnpViewPot = 27089
IDBpnpViewConc = 27090

def pnpPBSR( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Input Maps" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.BoxSizer( wx.HORIZONTAL )
    
    item4 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpSysTopFileNameIn, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="System Topology:",fileMask="*.systop",initialValue="S1_System.systop",history=["S1_System_Patched.systop","S1_System.systop"],fileMode=wx.FD_OPEN )
    item3.Add( item4, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item5 = wx.BoxSizer( wx.VERTICAL )
    
    item6 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpSRFileNameIn, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Soft Repultion:",fileMask="*.bin",initialValue="S1_SR.bin",history=["S1_SR.bin","None"],fileMode=wx.FD_OPEN )
    item5.Add( item6, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item1.Add( item5, 1, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item8 = wx.StaticBox( parent, -1, "Poisson-Boltzmann Soft Repulsion Parameters" )
    item7 = wx.StaticBoxSizer( item8, wx.VERTICAL )
    
    item9 = wx.BoxSizer( wx.HORIZONTAL )
    
    item10 = wx.StaticText( parent, ID_TEXTPNP, "Convergence:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item10, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item11 = wx.TextCtrl( parent, IDTCpnpPBSR_Tolerance, "0.0", wx.DefaultPosition, [80,-1], 0 )
    item9.Add( item11, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item12 = wx.StaticText( parent, ID_TEXTPNP, "Relaxation", wx.DefaultPosition, wx.DefaultSize, 0 )
    item9.Add( item12, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item13 = NumCtrl( parent, IDTCpnpPBSR_Relax, "1.6", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=0.0001,max=1.9999,integerWidth=1,fractionWidth=4,groupDigits=False )
    item9.Add( item13, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item7.Add( item9, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item14 = wx.BoxSizer( wx.HORIZONTAL )
    
    item15 = wx.StaticText( parent, ID_TEXTPNP, "Number of iterations:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item15, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item16 = NumCtrl( parent, IDTCpnpPBSR_Niter, "200", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=1,max=99999,integerWidth=5,fractionWidth=0,groupDigits=False )
    item14.Add( item16, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item7.Add( item14, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item0.Add( item7, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item18 = wx.StaticBox( parent, -1, "Output Maps" )
    item17 = wx.StaticBoxSizer( item18, wx.VERTICAL )
    
    item19 = wx.BoxSizer( wx.HORIZONTAL )
    
    item20 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpScriptFileName, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Script Filename:",fileMask="*.py",initialValue="S2_PBSR.py",history=["S1_CreateMaps.py"],fileMode=wx.FD_SAVE )
    item20.SetToolTip( wx.ToolTip("Script filename where maps creation instruction will be saved") )
    item19.Add( item20, 1, wx.ALIGN_CENTER, 5 )

    item17.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item21 = wx.BoxSizer( wx.HORIZONTAL )
    
    item22 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpPotFileNameOut, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Electrostatic Potential:",fileMask="*.bin",initialValue="S2_PBSR_Pot.bin",history=["S2_PBSR_Pot.bin","None"],fileMode=wx.FD_SAVE )
    item21.Add( item22, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item17.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item23 = wx.BoxSizer( wx.HORIZONTAL )
    
    item24 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpConcFileNameOut, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Concentrations:",fileMask="*.bin",initialValue="S2_PBSR_Conc.bin",history=["S2_PBSR_Conc.bin","None"],fileMode=wx.FD_SAVE )
    item23.Add( item24, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item17.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item25 = wx.BoxSizer( wx.HORIZONTAL )
    
    item27 = wx.StaticBox( parent, -1, "Run Control" )
    item26 = wx.StaticBoxSizer( item27, wx.VERTICAL )
    
    item28 = wx.BoxSizer( wx.HORIZONTAL )
    
    item29 = wx.Button( parent, IDBpnpSaveScript, "Save", wx.DefaultPosition, wx.DefaultSize, 0 )
    item29.SetToolTip( wx.ToolTip("Save Script") )
    item28.Add( item29, 0, wx.ALIGN_CENTER, 5 )

    item30 = wx.Button( parent, IDBpnpRunScript, "Save and Run", wx.DefaultPosition, wx.DefaultSize, 0 )
    item30.SetToolTip( wx.ToolTip("Save and Start Script Execution") )
    item28.Add( item30, 0, wx.ALIGN_CENTER, 5 )

    item26.Add( item28, 0, wx.ALIGN_CENTER, 5 )

    item31 = wx.BoxSizer( wx.HORIZONTAL )
    
    item32 = wx.Button( parent, IDBpnpInterruptScript, "Interrupt", wx.DefaultPosition, wx.DefaultSize, 0 )
    item32.SetToolTip( wx.ToolTip("interupt script execution") )
    item32.Enable(False)
    item31.Add( item32, 0, wx.ALIGN_CENTER, 5 )

    item33 = wx.Button( parent, IDBpnpStopScript, "Stop", wx.DefaultPosition, wx.DefaultSize, 0 )
    item33.SetToolTip( wx.ToolTip("Stop script execution") )
    item33.Enable(False)
    item31.Add( item33, 0, wx.ALIGN_CENTER, 5 )

    item26.Add( item31, 0, wx.ALIGN_CENTER, 5 )

    item25.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item35 = wx.StaticBox( parent, -1, "Results View" )
    item34 = wx.StaticBoxSizer( item35, wx.VERTICAL )
    
    item36 = wx.BoxSizer( wx.HORIZONTAL )
    
    item37 = wx.Button( parent, IDBpnpViewPot, "View Electrostatic Potential", wx.DefaultPosition, wx.DefaultSize, 0 )
    item36.Add( item37, 0, wx.ALIGN_CENTER, 5 )

    item38 = wx.Button( parent, IDBpnpViewConc, "View Concentrations", wx.DefaultPosition, wx.DefaultSize, 0 )
    item36.Add( item38, 0, wx.ALIGN_CENTER, 5 )

    item34.Add( item36, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item25.Add( item34, 1, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item0.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

IDTCpnpIAV_SysTopFileNameIN = 27091
IDTCpnpIAV_DiffFileNameIN = 27092
IDTCpnpIAV_SRFileName = 27093
IDTCpnpIAV_PotFileNameIN = 27094
IDTCpnpIAV_ConcFileNameIN = 27095
IDTCpnpIAV_MaxdC = 27096
IDTCpnpIAV_MaxCycles = 27097
IDTCpnpIAV_NP_Relax = 27098
IDTCpnpIAV_PBSR_Tolerance = 27099
IDTCpnpIAV_PBSR_Relax = 27100
IDTCpnpIAV_PBSR_Niter = 27101
IDTCpnpIAV_SysTopFileNameOUT = 27102
IDTCpnpIAV_DiffFileNameOUT = 27103
IDTCpnpIAV_PotFileNameOUT = 27104
IDTCpnpIAV_ConcFileNameOUT = 27105
IDBpnpIAV_Run = 27106
IDBpnpIAV_ViewPlainDiff = 27107
IDBpnpIAV_ViewDiff = 27108
IDBpnpIAV_ViewPot = 27109
IDBpnpIAV_ViewConc = 27110

def pnpIAVRef( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Input Files" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.BoxSizer( wx.HORIZONTAL )
    
    item4 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpIAV_SysTopFileNameIN, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="System Topology:",fileMask="*.systop",initialValue="S1_System_Patched.systop",history=["S1_System_Patched.systop","S1_System.systop"],fileMode=wx.FD_OPEN )
    item3.Add( item4, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item5 = wx.BoxSizer( wx.HORIZONTAL )
    
    item6 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpIAV_DiffFileNameIN, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Diffusion:",fileMask="*.bin",initialValue="S1_Diffusion_Patched.bin",history=["S1_Diffusion_Patched.bin","S1_Diffusion.bin","None"],fileMode=wx.FD_OPEN )
    item5.Add( item6, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item1.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item7 = wx.BoxSizer( wx.VERTICAL )
    
    item8 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpIAV_SRFileName, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Soft Repultion:",fileMask="*.bin",initialValue="S1_SR.bin",history=["S1_SR.bin","None"],fileMode=wx.FD_OPEN )
    item7.Add( item8, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.RIGHT, 5 )

    item1.Add( item7, 1, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item9 = wx.BoxSizer( wx.HORIZONTAL )
    
    item10 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpIAV_PotFileNameIN, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Electrostatic Potential (initial guess):",fileMask="*.bin",initialValue="S2_PBSR_Pot.bin",history=["S2_PBSR_Pot.bin"],fileMode=wx.FD_OPEN )
    item9.Add( item10, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item1.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11 = wx.BoxSizer( wx.HORIZONTAL )
    
    item12 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpIAV_ConcFileNameIN, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Concentrations:",fileMask="*.bin",initialValue="S2_PBSR_Conc.bin",history=["S2_PBSR_Conc.bin"],fileMode=wx.FD_OPEN )
    item11.Add( item12, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item1.Add( item11, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item14 = wx.StaticBox( parent, -1, "IAV Refinement Options" )
    item13 = wx.StaticBoxSizer( item14, wx.VERTICAL )
    
    item15 = wx.BoxSizer( wx.HORIZONTAL )
    
    item16 = wx.StaticText( parent, ID_TEXTPNP, "Maximal Concentration Change", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.Add( item16, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item17 = wx.TextCtrl( parent, IDTCpnpIAV_MaxdC, "0.0", wx.DefaultPosition, [80,-1], 0 )
    item15.Add( item17, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item18 = wx.StaticText( parent, ID_TEXTPNP, "Max. Number of Cycles:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item15.Add( item18, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item19 = NumCtrl( parent, IDTCpnpIAV_MaxCycles, "200", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=1,max=99999,integerWidth=5,fractionWidth=0,groupDigits=False )
    item15.Add( item19, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item13.Add( item15, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item20 = wx.BoxSizer( wx.HORIZONTAL )
    
    item21 = wx.StaticText( parent, ID_TEXTPNP, "Nernst Plank Solver Relaxation:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item20.Add( item21, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item22 = NumCtrl( parent, IDTCpnpIAV_NP_Relax, "1.6", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=0.0001,max=1.9999,integerWidth=1,fractionWidth=4,groupDigits=False )
    item20.Add( item22, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item13.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item24 = wx.StaticBox( parent, -1, "Poisson-Boltzmann Soft Repulsion Parameters" )
    item23 = wx.StaticBoxSizer( item24, wx.VERTICAL )
    
    item25 = wx.BoxSizer( wx.HORIZONTAL )
    
    item26 = wx.StaticText( parent, ID_TEXTPNP, "Convergence:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item25.Add( item26, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item27 = wx.TextCtrl( parent, IDTCpnpIAV_PBSR_Tolerance, "0.0", wx.DefaultPosition, [80,-1], 0 )
    item25.Add( item27, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item28 = wx.StaticText( parent, ID_TEXTPNP, "Relaxation:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item25.Add( item28, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item29 = NumCtrl( parent, IDTCpnpIAV_PBSR_Relax, "1.0", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=0.0001,max=1.9999,integerWidth=1,fractionWidth=4,groupDigits=False )
    item25.Add( item29, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item30 = wx.StaticText( parent, ID_TEXTPNP, "Number of iterations:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item25.Add( item30, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item31 = NumCtrl( parent, IDTCpnpIAV_PBSR_Niter, "200", wx.DefaultPosition, [80,-1], 0|wx.TE_RIGHT, min=1,max=99999,integerWidth=5,fractionWidth=0,groupDigits=False )
    item25.Add( item31, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item23.Add( item25, 0, wx.ALIGN_CENTER_VERTICAL|wx.ALL, 0 )

    item13.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item13, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item33 = wx.StaticBox( parent, -1, "Output Files" )
    item32 = wx.StaticBoxSizer( item33, wx.VERTICAL )
    
    item34 = wx.BoxSizer( wx.HORIZONTAL )
    
    item35 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpIAV_SysTopFileNameOUT, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="System Topology:",fileMask="*.systop",initialValue="S3_IAVRefined_System.systop",history=["S3_IAVRefined_System.systop"],fileMode=wx.FD_SAVE )
    item34.Add( item35, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item32.Add( item34, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item36 = wx.BoxSizer( wx.HORIZONTAL )
    
    item37 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpIAV_DiffFileNameOUT, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Diffusion:",fileMask="*.bin",initialValue="S3_IAVRefined_Diffusion.bin",history=["S3_IAVRefined_Diffusion.bin","None"],fileMode=wx.FD_SAVE )
    item36.Add( item37, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item32.Add( item36, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item38 = wx.BoxSizer( wx.HORIZONTAL )
    
    item39 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpIAV_PotFileNameOUT, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Electrostatic Potential:",fileMask="*.bin",initialValue="S3_IAVRefined_Pot.bin",history=["S3_IAVRefined_Pot.bin"],fileMode=wx.FD_SAVE )
    item38.Add( item39, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item32.Add( item38, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item40 = wx.BoxSizer( wx.HORIZONTAL )
    
    item41 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpIAV_ConcFileNameOUT, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Concentrations:",fileMask="*.bin",initialValue="S3_IAVRefined_Conc.bin",history=["S3_IAVRefined_Conc.bin"],fileMode=wx.FD_SAVE )
    item40.Add( item41, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item32.Add( item40, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item32, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item42 = wx.BoxSizer( wx.HORIZONTAL )
    
    item44 = wx.StaticBox( parent, -1, "Run Control" )
    item43 = wx.StaticBoxSizer( item44, wx.VERTICAL )
    
    item45 = wx.Button( parent, IDBpnpIAV_Run, "Run", wx.DefaultPosition, wx.DefaultSize, 0 )
    item43.Add( item45, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item42.Add( item43, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item47 = wx.StaticBox( parent, -1, "Results View" )
    item46 = wx.StaticBoxSizer( item47, wx.VERTICAL )
    
    item48 = wx.BoxSizer( wx.HORIZONTAL )
    
    item49 = wx.Button( parent, IDBpnpIAV_ViewPlainDiff, "View Plain Diffusion", wx.DefaultPosition, wx.DefaultSize, 0 )
    item49.SetToolTip( wx.ToolTip("This eventially initial IAV") )
    item48.Add( item49, 0, wx.ALIGN_CENTER, 5 )

    item50 = wx.Button( parent, IDBpnpIAV_ViewDiff, "View Diffusion", wx.DefaultPosition, wx.DefaultSize, 0 )
    item48.Add( item50, 0, wx.ALIGN_CENTER, 5 )

    item46.Add( item48, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item51 = wx.BoxSizer( wx.HORIZONTAL )
    
    item52 = wx.Button( parent, IDBpnpIAV_ViewPot, "View Electrostatic Potential", wx.DefaultPosition, wx.DefaultSize, 0 )
    item51.Add( item52, 0, wx.ALIGN_CENTER, 5 )

    item53 = wx.Button( parent, IDBpnpIAV_ViewConc, "View Concentrations", wx.DefaultPosition, wx.DefaultSize, 0 )
    item51.Add( item53, 0, wx.ALIGN_CENTER, 5 )

    item46.Add( item51, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item42.Add( item46, 1, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item0.Add( item42, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

IDBpnpCenterAtOrigin = 27111
ID_CHECKBOX = 27112
ID_BUTTON = 27113

def pnpPrepOld( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Shortcuts for Structure Manipulations" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.BoxSizer( wx.HORIZONTAL )
    
    item4 = wx.Button( parent, IDBpnpCenterAtOrigin, "Move Molecule to Origin", wx.DefaultPosition, wx.DefaultSize, 0 )
    item4.SetToolTip( wx.ToolTip("Move geometric center of molecule to coordinate origin") )
    item3.Add( item4, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item5 = wx.CheckBox( parent, ID_CHECKBOX, "Rotate Molecule, Not View", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item5, 0, wx.ALIGN_CENTER|wx.LEFT, 5 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item6 = wx.BoxSizer( wx.HORIZONTAL )
    
    item7 = wx.Button( parent, ID_BUTTON, "Delete All Waters", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item7, 0, wx.ALIGN_CENTER, 5 )

    item8 = wx.Button( parent, ID_BUTTON, "Delete All Hydrogens", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item8, 0, wx.ALIGN_CENTER, 5 )

    item9 = wx.Button( parent, ID_BUTTON, "Add All Missing Atoms", wx.DefaultPosition, wx.DefaultSize, 0 )
    item6.Add( item9, 0, wx.ALIGN_CENTER, 5 )

    item1.Add( item6, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item11 = wx.StaticBox( parent, -1, "Atomic Charges and Radii for Setting Internal  Dielectric Media" )
    item10 = wx.StaticBoxSizer( item11, wx.HORIZONTAL )
    
    item12 = wx.StaticText( parent, ID_TEXT, "Set Q and R using:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item10.Add( item12, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item13 = wx.Choice( parent, IDCpnpFF4QRdiel, wx.DefaultPosition, [100,-1], [], 0 )
    item10.Add( item13, 1, wx.ALIGN_CENTER, 5 )

    item0.Add( item10, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item15 = wx.StaticBox( parent, -1, "Atomic Ion Excluded Radius for Setting Initial Ion Accessible Volume" )
    item14 = wx.StaticBoxSizer( item15, wx.HORIZONTAL )
    
    item16 = wx.StaticText( parent, ID_TEXT, "Add Ion Radii :  ", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item16, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item17 = wx.StaticText( parent, ID_TEXT, "Ion1", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item17, 0, wx.ALIGN_CENTER, 5 )

    item18 = wx.TextCtrl( parent, IDTCpnpAddRion1, "0.5", wx.DefaultPosition, [80,-1], 0 )
    item14.Add( item18, 0, wx.ALIGN_CENTER, 5 )

    item19 = wx.StaticText( parent, ID_TEXT, "Angstroms", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item19, 0, wx.ALIGN_CENTER, 5 )

    item20 = wx.StaticText( parent, ID_TEXT, "Ion2", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item20, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item21 = wx.TextCtrl( parent, IDTCpnpAddRion2, "0.5", wx.DefaultPosition, [80,-1], 0 )
    item14.Add( item21, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item22 = wx.StaticText( parent, ID_TEXT, "Angstroms", wx.DefaultPosition, wx.DefaultSize, 0 )
    item14.Add( item22, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item0.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item24 = wx.StaticBox( parent, -1, "Atomic Soft Repulsion Parameters" )
    item23 = wx.StaticBoxSizer( item24, wx.HORIZONTAL )
    
    item25 = wx.StaticText( parent, ID_TEXT, "Set Soft Repulsion Parameters using:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item23.Add( item25, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item26 = wx.Choice( parent, IDCpnpFF4SR, wx.DefaultPosition, [100,-1], [], 0 )
    item23.Add( item26, 1, wx.ALIGN_CENTER, 5 )

    item0.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item27 = wx.StaticLine( parent, ID_LINE, wx.DefaultPosition, [20,-1], wx.LI_HORIZONTAL )
    item0.Add( item27, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item29 = wx.StaticBox( parent, -1, "Parameters" )
    item28 = wx.StaticBoxSizer( item29, wx.VERTICAL )
    
    item30 = wx.BoxSizer( wx.HORIZONTAL )
    
    item31 = wx.Button( parent, IDBpnpSetParam, "Set Parameters", wx.DefaultPosition, wx.DefaultSize, 0 )
    item30.Add( item31, 0, wx.ALIGN_CENTER, 5 )

    item30.Add( [ 60, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item32 = wx.TextCtrl( parent, IDTCpnpAtmParFileName, "system.atmpar", wx.DefaultPosition, [80,-1], 0 )
    item30.Add( item32, 1, wx.ALIGN_CENTER, 5 )

    item33 = wx.Button( parent, IDBpnpSaveAtmPar, "Save Atomic Parameters", wx.DefaultPosition, wx.DefaultSize, 0 )
    item30.Add( item33, 0, wx.ALIGN_CENTER, 5 )

    item28.Add( item30, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item34 = wx.grid.Grid( parent, IDGpnpAtomParam, wx.DefaultPosition, [200,160], wx.WANTS_CHARS )
    item28.Add( item34, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item0.Add( item28, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

IDTCpnpPM_SysTopFileNameIN = 27114
IDTCpnpPM_DiffFileNameIN = 27115
IDBpnpPM_LoadMaps = 27116
IDNpnpPM_DielOrDiffPatch = 27117
IDTCpnpPM_SysTopFileNameOUT = 27118
IDTCpnpPM_DiffFileNameOUT = 27119
IDBpnpPatchMaps = 27120
IDBpnpPM_ViewStaticCharge = 27121
IDBpnpPM_ViewDiel = 27122
IDBpnpPM_ViewPlainDiff = 27123
IDBpnpPM_ViewDiff = 27124

def pnpMapPatch( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Input Files" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.BoxSizer( wx.HORIZONTAL )
    
    item4 = wx.BoxSizer( wx.VERTICAL )
    
    item5 = wx.BoxSizer( wx.HORIZONTAL )
    
    item6 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpPM_SysTopFileNameIN, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="System Topology:",fileMask="*.systop",initialValue="S1_System.systop",history=["S1_System.systop"],fileMode=wx.FD_OPEN )
    item5.Add( item6, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item4.Add( item5, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item7 = wx.BoxSizer( wx.HORIZONTAL )
    
    item8 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpPM_DiffFileNameIN, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Diffusion:",fileMask="*.bin",initialValue="S1_Diffusion.bin",history=["S1_Diffusion.bin","None"],fileMode=wx.FD_OPEN )
    item7.Add( item8, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item4.Add( item7, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item3.Add( item4, 1, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item9 = wx.BoxSizer( wx.VERTICAL )
    
    item10 = wx.Button( parent, IDBpnpPM_LoadMaps, 
        "Load Maps\n"
        "Info",
        wx.DefaultPosition, [-1,40], 0 )
    item10.SetToolTip( wx.ToolTip("Load Dielectric constants values from maps") )
    item9.Add( item10, 0, wx.ALIGN_CENTER_VERTICAL, 5 )

    item3.Add( item9, 0, wx.ALIGN_CENTER, 5 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item12 = wx.Notebook( parent, IDNpnpPM_DielOrDiffPatch, wx.DefaultPosition, [200,160], 0 )
    item11 = item12
    
    item0.Add( item11, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item14 = wx.StaticBox( parent, -1, "Output Files" )
    item13 = wx.StaticBoxSizer( item14, wx.VERTICAL )
    
    item15 = wx.BoxSizer( wx.HORIZONTAL )
    
    item16 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpPM_SysTopFileNameOUT, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="System Topology:",fileMask="*.systop",initialValue="S1_System_Patched.systop",history=["S1_System_Patched.systop","None"],fileMode=wx.FD_SAVE )
    item15.Add( item16, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item13.Add( item15, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item17 = wx.BoxSizer( wx.HORIZONTAL )
    
    item18 = filebrowse.FileBrowseButtonWithHistory( parent, IDTCpnpPM_DiffFileNameOUT, wx.DefaultPosition, wx.DefaultSize, 0|524288,labelText="Diffusion:",fileMask="*.bin",initialValue="S1_Diffusion_Patched.bin",history=["S1_Diffusion_Patched.bin","None"],fileMode=wx.FD_SAVE )
    item17.Add( item18, 1, wx.ALIGN_CENTER|wx.RIGHT, 5 )

    item13.Add( item17, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item13, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item19 = wx.BoxSizer( wx.HORIZONTAL )
    
    item21 = wx.StaticBox( parent, -1, "Run Control" )
    item20 = wx.StaticBoxSizer( item21, wx.VERTICAL )
    
    item22 = wx.Button( parent, IDBpnpPatchMaps, "Patch Maps", wx.DefaultPosition, wx.DefaultSize, 0 )
    item20.Add( item22, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item19.Add( item20, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item24 = wx.StaticBox( parent, -1, "Results View" )
    item23 = wx.StaticBoxSizer( item24, wx.VERTICAL )
    
    item25 = wx.BoxSizer( wx.HORIZONTAL )
    
    item26 = wx.Button( parent, IDBpnpPM_ViewStaticCharge, "View Static Charge", wx.DefaultPosition, wx.DefaultSize, 0 )
    item25.Add( item26, 0, wx.ALIGN_CENTER, 5 )

    item27 = wx.Button( parent, IDBpnpPM_ViewDiel, "View Dielectric Constants", wx.DefaultPosition, wx.DefaultSize, 0 )
    item25.Add( item27, 0, wx.ALIGN_CENTER, 5 )

    item23.Add( item25, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item28 = wx.BoxSizer( wx.HORIZONTAL )
    
    item29 = wx.Button( parent, IDBpnpPM_ViewPlainDiff, "View Plain Diffusion", wx.DefaultPosition, wx.DefaultSize, 0 )
    item29.SetToolTip( wx.ToolTip("This eventially initial IAV") )
    item28.Add( item29, 0, wx.ALIGN_CENTER, 5 )

    item30 = wx.Button( parent, IDBpnpPM_ViewDiff, "View Diffusion", wx.DefaultPosition, wx.DefaultSize, 0 )
    item28.Add( item30, 0, wx.ALIGN_CENTER, 5 )

    item23.Add( item28, 1, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item19.Add( item23, 0, wx.GROW|wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item0.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

ID_RADIOBUTTON = 27125

def pnpPNPSRold( parent, call_fit = True, set_sizer = True ):
    item0 = wx.BoxSizer( wx.VERTICAL )
    
    item2 = wx.StaticBox( parent, -1, "Input Maps" )
    item1 = wx.StaticBoxSizer( item2, wx.VERTICAL )
    
    item3 = wx.BoxSizer( wx.HORIZONTAL )
    
    item4 = wx.RadioButton( parent, ID_RADIOBUTTON, "Browse", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item4, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item5 = wx.RadioButton( parent, ID_RADIOBUTTON, "Use Previously Built", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item5, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item6 = wx.RadioButton( parent, ID_RADIOBUTTON, "Use Prefix", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item6, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item3.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item7 = wx.StaticText( parent, ID_TEXT, "Prefix", wx.DefaultPosition, wx.DefaultSize, 0 )
    item3.Add( item7, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item8 = wx.TextCtrl( parent, ID_TEXTCTRL, "", wx.DefaultPosition, [80,-1], 0 )
    item3.Add( item8, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item1.Add( item3, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item9 = wx.BoxSizer( wx.HORIZONTAL )
    
    item10 = wx.StaticText( parent, ID_TEXT, "System Topology:", wx.DefaultPosition, [100,-1], 0 )
    item9.Add( item10, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item11 = wx.TextCtrl( parent, ID_TEXTCTRL, "ahl_IAVRef_SysTop.gz", wx.DefaultPosition, [140,-1], 0 )
    item9.Add( item11, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item12 = wx.StaticText( parent, ID_TEXT, "El. Potential", wx.DefaultPosition, [100,-1], 0 )
    item9.Add( item12, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item13 = wx.TextCtrl( parent, ID_TEXTCTRL, "ahl_IAVRef_Pot.bin", wx.DefaultPosition, [140,-1], 0 )
    item9.Add( item13, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item1.Add( item9, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item14 = wx.BoxSizer( wx.HORIZONTAL )
    
    item15 = wx.StaticText( parent, ID_TEXT, "SR Potential:", wx.DefaultPosition, [100,-1], 0 )
    item14.Add( item15, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item16 = wx.TextCtrl( parent, ID_TEXTCTRL, "ahl_SR.bin", wx.DefaultPosition, [140,-1], 0 )
    item14.Add( item16, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item17 = wx.StaticText( parent, ID_TEXT, "Concentrations:", wx.DefaultPosition, [100,-1], 0 )
    item14.Add( item17, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item18 = wx.TextCtrl( parent, ID_TEXTCTRL, "ahl_IAVRef_C.bin", wx.DefaultPosition, [140,-1], 0 )
    item14.Add( item18, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item1.Add( item14, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item1, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item20 = wx.StaticBox( parent, -1, "Applied Potential" )
    item19 = wx.StaticBoxSizer( item20, wx.VERTICAL )
    
    item21 = wx.BoxSizer( wx.HORIZONTAL )
    
    item22 = wx.RadioButton( parent, ID_RADIOBUTTON, "Apply Linear Drop Along Membrane", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.Add( item22, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item21.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item23 = wx.StaticText( parent, ID_TEXT, "Potential Diffrence", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.Add( item23, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item24 = wx.TextCtrl( parent, ID_TEXTCTRL, "80.0", wx.DefaultPosition, [80,-1], 0 )
    item21.Add( item24, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item25 = wx.StaticText( parent, ID_TEXT, "mV", wx.DefaultPosition, wx.DefaultSize, 0 )
    item21.Add( item25, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item19.Add( item21, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item26 = wx.BoxSizer( wx.HORIZONTAL )
    
    item27 = wx.RadioButton( parent, ID_RADIOBUTTON, "Select Linear Drop Manually", wx.DefaultPosition, wx.DefaultSize, 0 )
    item26.Add( item27, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item26.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item28 = wx.StaticText( parent, ID_TEXT, "z0:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item26.Add( item28, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item29 = wx.TextCtrl( parent, ID_TEXTCTRL, "-45.0", wx.DefaultPosition, [40,-1], 0 )
    item26.Add( item29, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item30 = wx.StaticText( parent, ID_TEXT, "Ang.  z1:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item26.Add( item30, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item31 = wx.TextCtrl( parent, ID_TEXTCTRL, "-17", wx.DefaultPosition, [40,-1], 0 )
    item26.Add( item31, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item32 = wx.StaticText( parent, ID_TEXT, "Ang.  Phi0:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item26.Add( item32, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item33 = wx.TextCtrl( parent, ID_TEXTCTRL, "80.0", wx.DefaultPosition, [40,-1], 0 )
    item26.Add( item33, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item34 = wx.StaticText( parent, ID_TEXT, "mV  Phi1", wx.DefaultPosition, wx.DefaultSize, 0 )
    item26.Add( item34, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item35 = wx.TextCtrl( parent, ID_TEXTCTRL, "0.0", wx.DefaultPosition, [40,-1], 0 )
    item26.Add( item35, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item36 = wx.StaticText( parent, ID_TEXT, "mV", wx.DefaultPosition, wx.DefaultSize, 0 )
    item26.Add( item36, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item19.Add( item26, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item19, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item38 = wx.StaticBox( parent, -1, "Solver Parameters" )
    item37 = wx.StaticBoxSizer( item38, wx.VERTICAL )
    
    item39 = wx.BoxSizer( wx.HORIZONTAL )
    
    item40 = wx.StaticText( parent, ID_TEXT, "Max. PNP Cycles", wx.DefaultPosition, wx.DefaultSize, 0 )
    item39.Add( item40, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item41 = wx.TextCtrl( parent, ID_TEXTCTRL, "1000", wx.DefaultPosition, [80,-1], 0 )
    item39.Add( item41, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item39.Add( [ 20, 20 ] , 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item42 = wx.StaticText( parent, ID_TEXT, "Current Tolerance", wx.DefaultPosition, wx.DefaultSize, 0 )
    item39.Add( item42, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item43 = wx.TextCtrl( parent, ID_TEXTCTRL, "0.0", wx.DefaultPosition, [80,-1], 0 )
    item39.Add( item43, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item44 = wx.StaticText( parent, ID_TEXT, "pA", wx.DefaultPosition, wx.DefaultSize, 0 )
    item39.Add( item44, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item37.Add( item39, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item45 = wx.BoxSizer( wx.HORIZONTAL )
    
    item46 = wx.StaticText( parent, ID_TEXT, "PE Iterations:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item45.Add( item46, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item47 = wx.TextCtrl( parent, ID_TEXTCTRL, "20", wx.DefaultPosition, [40,-1], 0 )
    item45.Add( item47, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item48 = wx.StaticText( parent, ID_TEXT, "PE Relaxation:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item45.Add( item48, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item49 = wx.TextCtrl( parent, ID_TEXTCTRL, "1.5", wx.DefaultPosition, [40,-1], 0 )
    item45.Add( item49, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item50 = wx.StaticText( parent, ID_TEXT, "NPE Iterations:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item45.Add( item50, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item51 = wx.TextCtrl( parent, ID_TEXTCTRL, "20", wx.DefaultPosition, [40,-1], 0 )
    item45.Add( item51, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item52 = wx.StaticText( parent, ID_TEXT, "NPE Relaxation:", wx.DefaultPosition, wx.DefaultSize, 0 )
    item45.Add( item52, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item53 = wx.TextCtrl( parent, ID_TEXTCTRL, "1.5", wx.DefaultPosition, [40,-1], 0 )
    item45.Add( item53, 1, wx.ALIGN_CENTER|wx.ALL, 5 )

    item37.Add( item45, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item0.Add( item37, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item55 = wx.StaticBox( parent, -1, "Run Control and Results" )
    item54 = wx.StaticBoxSizer( item55, wx.HORIZONTAL )
    
    item56 = wx.BoxSizer( wx.VERTICAL )
    
    item56.Add( [ 25, 25 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item57 = wx.StaticText( parent, ID_TEXT, "Current, pA", wx.DefaultPosition, wx.DefaultSize, 0 )
    item56.Add( item57, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item58 = wx.StaticText( parent, ID_TEXT, "Std.Dev., pA", wx.DefaultPosition, wx.DefaultSize, 0 )
    item56.Add( item58, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item54.Add( item56, 0, wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item59 = wx.BoxSizer( wx.VERTICAL )
    
    item60 = wx.StaticText( parent, ID_TEXT, "Total", wx.DefaultPosition, wx.DefaultSize, 0 )
    item59.Add( item60, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item61 = wx.TextCtrl( parent, ID_TEXTCTRL, "20.58", wx.DefaultPosition, [80,-1], 0 )
    item59.Add( item61, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item62 = wx.TextCtrl( parent, ID_TEXTCTRL, "5.8E-04", wx.DefaultPosition, [80,-1], 0 )
    item59.Add( item62, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item54.Add( item59, 1, wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item63 = wx.BoxSizer( wx.VERTICAL )
    
    item64 = wx.StaticText( parent, ID_TEXT, "Ions0", wx.DefaultPosition, wx.DefaultSize, 0 )
    item63.Add( item64, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item65 = wx.TextCtrl( parent, ID_TEXTCTRL, "3.92", wx.DefaultPosition, [80,-1], 0 )
    item63.Add( item65, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item66 = wx.TextCtrl( parent, ID_TEXTCTRL, "1.3E-04", wx.DefaultPosition, [80,-1], 0 )
    item63.Add( item66, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item54.Add( item63, 1, wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item67 = wx.BoxSizer( wx.VERTICAL )
    
    item68 = wx.StaticText( parent, ID_TEXT, "Ions2", wx.DefaultPosition, wx.DefaultSize, 0 )
    item67.Add( item68, 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item69 = wx.TextCtrl( parent, ID_TEXTCTRL, "16.65", wx.DefaultPosition, [80,-1], 0 )
    item67.Add( item69, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item70 = wx.TextCtrl( parent, ID_TEXTCTRL, "4.5E-04", wx.DefaultPosition, [80,-1], 0 )
    item67.Add( item70, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL|wx.ALL, 5 )

    item54.Add( item67, 1, wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item54.Add( [ 20, 20 ] , 0, wx.ALIGN_CENTER|wx.ALL, 5 )

    item71 = wx.BoxSizer( wx.VERTICAL )
    
    item72 = wx.Button( parent, IDBpnpPNPSR_Run, "Run PNP-SR", wx.DefaultPosition, wx.DefaultSize, 0 )
    item71.Add( item72, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item73 = wx.Button( parent, ID_BUTTON, "View Potential", wx.DefaultPosition, wx.DefaultSize, 0 )
    item71.Add( item73, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    item74 = wx.Button( parent, ID_BUTTON, "View Concentrations", wx.DefaultPosition, wx.DefaultSize, 0 )
    item71.Add( item74, 0, wx.ALIGN_CENTER, 5 )

    item54.Add( item71, 0, wx.ALIGN_CENTER_HORIZONTAL, 5 )

    item0.Add( item54, 0, wx.GROW|wx.ALIGN_CENTER_VERTICAL, 5 )

    if set_sizer == True:
        parent.SetSizer( item0 )
        if call_fit == True:
            item0.SetSizeHints( parent )
    
    return item0

# Menubar functions

# Toolbar functions

# Bitmap functions


# End of generated file
