<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <PYTHON_HOME_PATH>D:\Python312</PYTHON_HOME_PATH>
    <PYTHON_BIN_PATH>$(PYTHON_HOME_PATH)</PYTHON_BIN_PATH>
    <PYTHON_DLLS_PATH>$(PYTHON_HOME_PATH)</PYTHON_DLLS_PATH>
    <PHOENIX_PATH>D:\MYPROG\Phoenix_4.2.5_P312</PHOENIX_PATH>
    <WX_DLLS_PATH>$(PHOENIX_PATH)\ext\wxWidgets\lib\vc140_x64_dll</WX_DLLS_PATH>
    <WX_INCLUDE_PATH>$(PHOENIX_PATH)\ext\wxWidgets\include</WX_INCLUDE_PATH>
    <PLPLOT_DLLS_PATH>$(VCPKG_DLL)</PLPLOT_DLLS_PATH>
    <WX_VERSION>33u</WX_VERSION>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(PYTHON_HOME_PATH)\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(PYTHON_HOME_PATH)\libs;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="PYTHON_HOME_PATH">
      <Value>$(PYTHON_HOME_PATH)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="PYTHON_BIN_PATH">
      <Value>$(PYTHON_BIN_PATH)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="PYTHON_DLLS_PATH">
      <Value>$(PYTHON_DLLS_PATH)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="PHOENIX_PATH">
      <Value>$(PHOENIX_PATH)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="WX_DLLS_PATH">
      <Value>$(WX_DLLS_PATH)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="WX_INCLUDE_PATH">
      <Value>$(WX_INCLUDE_PATH)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="PLPLOT_DLLS_PATH">
      <Value>$(PLPLOT_DLLS_PATH)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
    <BuildMacro Include="WX_VERSION">
      <Value>$(WX_VERSION)</Value>
      <EnvironmentVariable>true</EnvironmentVariable>
    </BuildMacro>
  </ItemGroup>
</Project>