######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 12 09:08:44 2006
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ..
CONFIG += staticlib

# Input
SOURCES += atom.cpp bond.cpp head.cpp resd.cpp sect.cpp
