{% set version = "21.03.29" %}

package:
  name: molset
  version: {{ version }}

source:
  path: ../../MOLSET_BIN_LIBS
  
requirements:
  build:
    - python
    - setuptools
    
  run:
    - python
    - pip    

outputs:
  - name: harlem 
    version: {{ version }}
  - name: molset
    version: {{ version }}


