{% set version = "25.07.16" %}

package:
  name: molset
  version: {{ version }}

source:
  path: ../../MOLSET_BIN_LIBS
  
requirements:
  build:
    - python
    - setuptools
    
  run:
    - python
    - pip    

