include ./../../HALIB/Makefile.inc
#DELPHI_LIB is located in Makefile.inc
#DELPHI_LIB=$(PACKAGE_DIR)/lib/delphi_lib$(SUFFIX).a
OPTS    = -c -O3 -ffixed-line-length-132 
#OPTS    = -c -O3 -ffixed-line-length-132 

OBJ=    \
itit4j.o non.o relfac4b.o setcrg4.o \
mem4.o phintp4.o scaler4.o setin4.o \
mkeps4f.o qdiff4s.o setbc4.o setout4.o

all: delphi_lib

delphi_lib: $(OBJ)
	ar cr $(DELPHI_LIB) $(OBJ) 

clean:
	rm -f *.o

%.o : %.f 
	$(FORT) $(OPTS) -c $*.f


