######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 10 19:15:00 2006
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ..
CONFIG += staticlib

# Input
HEADERS += second.hpp
SOURCES += atom.cpp build.cpp second.cpp
