mset = GetCurMolSet()
qc_mod = mset.GetQCMod(1)
gauss_mod = mset.GetGaussMod(1)
zm = qc_mod.GetZMat()
zm.UnFreezeCrdAll()
#alpha = zm.GetCrdByTag("alpha")
#theta = zm.GetCrdByTag("theta")
#alpha.SetFrozen()
#theta.SetFrozen()
#zm.SetAtomCrd()
#zm.SetFromAtomCrd() 
qc_mod.InitBasis("6-31G(d)")
qc_mod.SetCharge(0)
qc_mod.SetEneMinCalc()
gauss_mod.SetNumSharedMemCores(4)
qc_mod.Run()
print "ene = ",qc_mod.GetEne()

