import sys
sys.path.append("c:\\python20")
sys.path.append("c:\\python20\\Lib")
sys.path.append("c:\\scripps_pylib")
sys.path.append("c:\\scripps_pylib\\Numeric")
sys.path.append("c:\\scripps_pylib\\mslib")
import mslib
m = mslib.MSMS(filename="benz2_br2_1.xyzr")  
m.compute()
m.compute_ses()
m.compute_ses_area()
print(m.info())
(vfloat, vint, tri) = m.getTriangles()
print("vfloat size=",len(vfloat))
print(vfloat[0])
print("vint size=",len(vint))
print(vint[0])
print("tri size=",len(tri))
print(tri[0])
